#+title: Homo Deus
A Brief History of Tomorrow


* The Agenda

** for thousands of years

*** 3 problems

**** famine

**** plague

**** war

** in the third millenium

*** we rein in the problems
    these problems were understood to be in humanity's control
    - no more praying
    - if something goes wrong: who screwed up?

*** we have new-found power
    what will we do with it, what's the new item on the agenda

** the Biological Poverty Line
    - in the last hundread years progress has created an increasingly robust safety net separating humankind and the Biological Poverty Line
      + very few people now die of hunger (in most parts of the world)
        - still 10% of France population live in eating insecurity, not knowing what they'll eat
          + what they eat is bad for their health
    - The Great Leap Forward
      + during the World Food Conference in Rome 1974 leaders were told China had no way to feed its billion people
        - although in reality it's the first time China has no famine

** Invisible Armadas
    _Yersinia Pestis_
    - Somewhere in central Asia - 1330s
      + from fleas
      + =Black Death=
        - 75 - 200 M deaths | 1/4 of Eurasia
    _Smallpox_
    - Conquistadores - America - 1520
      + The slave Frncisco de Eguia was ill
      + The day after their arrival locals started dying
    - between that and others illnesses 90% of the local population died
    _Tubercolosis_
    - James Cook - Hawai - 1778
    _The Spanish Flu_
    - Trenches - WW1

    In Modern times humanity is more supseptible to diseases because of better transportation and growing population
    But:
    - child mortality all-time low: <5% deaths
    - vaccines eradicated smallpox in 1979
    _AIDS_
    - the only seemengly real failure of medicine in modern times

    While pathogens depend on luck: mutations to jump species and resist antibiotics; Doctors count on more than mere luck

    The WHO is harshly criticized for the sligthest misstep; we don't blame divinities anymore.
    We seem to be winning the race with pathogens
    It seems more likely that the same knowledge that enables us to fight these illnesses would destroy us if used for war, in the service of some ideology

** Breaking the Law of the Jungle
    Wars too are disappearing
    - Sugar is more dangerous than gunpowder
      + 2012
        - 56M deaths in the world
        - violence 620k
          + war 120k
          + crime 500k
        - 800k suicides
        - 1.5M died of diabetes

    War is inconcevable to most
    - the nuclear stall transformed war into mass suicide
      + powerful nations now consider alternative, peaceful options

    ~Material-based~ economy VS =Knowledge-based= economy
    - in the past sources of wealth
      + assets, gold, fields, oil
        - can be conquered through war
    - now knowledge is wealth
      + Rwanda looted coltan from Congo and made $240 a year
      + China makes that cooperating with Apple and Microsoft, manufactoring their products

    This =New Peace= now means the implausibility of war
    - we can't see any scenarios of real war between most developed countries
    - companies invest counting on this

    There are still threats
    - Logic Bombs are now a possibility
      + though ability =/= motivation
        - =Chekhov Law= was broken too in fact
          + the new weapon appeared during the Cold War was never fired
    - Terrorism
      + weapon of weakness of those who lack real power
        - they work on fear because of lack of material damage
      + Its a show/spectacle
      + the fly cannot by itself destry the china shop, if it buzzes in the bull's ear though its rage will do its work for it
        - Islamic Fundamentalists did this with 9/11, now thriving in destroyed Middle East

    The true enemy is now human destruction on our own planet
    - most always prefered growth to ecological stability
    - humans are never satisfied and want more and more

    Having overcomed disease, famine and war the next aims of humanity will be overcoming death, achiving happiness and putting past us our beastly survival struggles, upgrading Homo Sapiens into =Homo Deus=

   - [[file:20200531055420-quotes.org][cit]]
       Success breeds ambition, and our recent achievements are now pushing humankind to set itself even more daring goals. Having secured unprecedented levels of prosperity, health and harmony, and given our past record and our current values, humanity’s next targets are likely to be immortality, happiness and divinity. Having reduced mortality from starvation, disease and violence, we will now aim to overcome old age and even death itself. Having saved people from abject misery, we will now aim to make them positively happy. And having raised humanity above the beastly level of survival struggles, we will now aim to upgrade humans into gods, and turn Home sapiens into Homo deus.

** Death & Immortality

*** The right to live
    Universal right

**** Death goes against this
    Crime against humanity, =A technical problem to solve=
    This was not the case in the past
    - religions and ideologies sanctified Death not Life
        the focus was on the afterlife and Death was vital in that sense
    We now understand the technical nature of Death

    - Death is now associed with a mistake, not with a cosmic plan

**** Consequenses
    * Social structures would have to change
      + marriages won't be forever
    * Elder people won't leave way to the youth so easily
      + [[file:20200531055420-quotes.org][cit]]: Science advances one funeral at the time ~ Max Planck

*** But in reality science won't solve Death in the foreseable future
    The life-span of humans hasn't changed, we got better at preventing premature death

*** On immortality
:PROPERTIES:
:NOTER_DOCUMENT: /home/dan/Dropbox/Books/EBooks/Homo Deus_ A Brief History of Tomorrow - Yuval Noah Harari.epub
:NOTER_PAGE: (6 . 8757)
:END:
- [[file:20200531055420-quotes.org][cit]]
    I don't want to achieve immortality through my work. I want to achieve it by not dying. ~ Woody Allen

Questa e' una nota.



Ciao


Un altra nota.



* The Conquest

* The Meaning

* The Control
