#+title: Homo Deus
[[file:20201029112426-books.org][$books]]
Harari, Noha, Yuval, /Home Deus: A brief History of Tomorrow/, Dvir publishing, 2015, pp.448


* The Agenda

** for thousands of years

*** 3 problems

**** famine

**** plague

**** war

** in the third millenium

*** we rein in the problems
    these problems were understood to be in humanity's control
    - no more praying
    - if something goes wrong: who screwed up?

*** we have new-found power
    what will we do with it, what's the new item on the agenda

** the Biological Poverty Line
    - in the last hundread years progress has created an increasingly robust safety net separating humankind and the Biological Poverty Line
      + very few people now die of hunger (in most parts of the world)
        - still 10% of France population live in eating insecurity, not knowing what they'll eat
          + what they eat is bad for their health
    - The Great Leap Forward
      + during the World Food Conference in Rome 1974 leaders were told China had no way to feed its billion people
        - although in reality it's the first time China has no famine

** Invisible Armadas
    _Yersinia Pestis_
    - Somewhere in central Asia - 1330s
      + from fleas
      + =Black Death=
        - 75 - 200 M deaths | 1/4 of Eurasia
    _Smallpox_
    - Conquistadores - America - 1520
      + The slave Frncisco de Eguia was ill
      + The day after their arrival locals started dying
    - between that and others illnesses 90% of the local population died
    _Tubercolosis_
    - James Cook - Hawai - 1778
    _The Spanish Flu_
    - Trenches - WW1

    In Modern times humanity is more supseptible to diseases because of better transportation and growing population
    But:
    - child mortality all-time low: <5% deaths
    - vaccines eradicated smallpox in 1979
    _AIDS_
    - the only seemengly real failure of medicine in modern times

    While pathogens depend on luck: mutations to jump species and resist antibiotics; Doctors count on more than mere luck

    The WHO is harshly criticized for the sligthest misstep; we don't blame divinities anymore.
    We seem to be winning the race with pathogens
    It seems more likely that the same knowledge that enables us to fight these illnesses would destroy us if used for war, in the service of some ideology

** Breaking the Law of the Jungle
    Wars too are disappearing
    - Sugar is more dangerous than gunpowder
      + 2012
        - 56M deaths in the world
        - violence 620k
          + war 120k
          + crime 500k
        - 800k suicides
        - 1.5M died of diabetes

    War is inconcevable to most
    - the nuclear stall transformed war into mass suicide
      + powerful nations now consider alternative, peaceful options

    ~Material-based~ economy VS =Knowledge-based= economy
    - in the past sources of wealth
      + assets, gold, fields, oil
        - can be conquered through war
    - now knowledge is wealth
      + Rwanda looted coltan from Congo and made $240 a year
      + China makes that cooperating with Apple and Microsoft, manufactoring their products

    This =New Peace= now means the implausibility of war
    - we can't see any scenarios of real war between most developed countries
    - companies invest counting on this

    There are still threats
    - Logic Bombs are now a possibility
      + though ability =/= motivation
        - =Chekhov Law= was broken too in fact
          + the new weapon appeared during the Cold War was never fired
    - Terrorism
      + weapon of weakness of those who lack real power
        - they work on fear because of lack of material damage
      + Its a show/spectacle
      + the fly cannot by itself destry the china shop, if it buzzes in the bull's ear though its rage will do its work for it
        - Islamic Fundamentalists did this with 9/11, now thriving in destroyed Middle East

    The true enemy is now human destruction on our own planet
    - most always prefered growth to ecological stability
    - humans are never satisfied and want more and more

    Having overcomed disease, famine and war the next aims of humanity will be overcoming death, achiving happiness and putting past us our beastly survival struggles, upgrading Homo Sapiens into =Homo Deus=

   - [[file:20210604132601-cit.org][Quotes]]
       Success breeds ambition, and our recent achievements are now pushing humankind to set itself even more daring goals. Having secured unprecedented levels of prosperity, health and harmony, and given our past record and our current values, humanity’s next targets are likely to be immortality, happiness and divinity. Having reduced mortality from starvation, disease and violence, we will now aim to overcome old age and even death itself. Having saved people from abject misery, we will now aim to make them positively happy. And having raised humanity above the beastly level of survival struggles, we will now aim to upgrade humans into gods, and turn Home sapiens into Homo deus.

** Death & Immortality

*** The right to live
    Universal right

**** Death goes against this
    Crime against humanity, =A technical problem to solve=
    This was not the case in the past
    - religions and ideologies sanctified Death not Life
        the focus was on the afterlife and Death was vital in that sense
    We now understand the technical nature of Death

    - Death is now associed with a mistake, not with a cosmic plan

**** Consequenses
    * Social structures would have to change
      + marriages won't be forever
    * Elder people won't leave way to the youth so easily
      + [[file:20210604132601-cit.org][Quotes]]
          Science advances one funeral at the time ~ Max Planck

*** But in reality science won't solve Death in the foreseable future
    The life-span of humans hasn't changed, we got better at preventing premature death

*** On immortality
:PROPERTIES:
:NOTER_PAGE: (9 . 10303)
:END:
- [[file:20210604132601-cit.org][Quotes]]
    I don't want to achieve immortality through my work. I want to achieve it by not dying. ~ Woody Allen


- Immortality is the ultimate objective of humanism (the worship of humankind)
  - this is the agenda of humankind in the end as the humanism has conquered the world

hy did this happen? Why has humanism become the dominant world religion and why attempting to fulfil the idead this religion proposes is likely to cause our disentegration
- to humanism:
  + humans are at the center of the universe
  + humans are the source of meaning and authority


* The Conquest
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Dropbox/Books/EBooks/Homo Deus_ A Brief History of Tomorrow - Yuval Noah Harari.epub
:NOTER_PAGE: (10 . 676)
:END:

*** Humans and Animals
Animals are disappearing in reality, they survive in our delusion
    - there are much more domestic animals then their wild counterpart
      + testifying the humans influence on nature

    Epochs: =Pleistocene, Pliocene, Miocene, Holocene=
    But really =Anthropocene= never a single species managed to change the global
    economy at this extent
    - our impact is already on par with
      - ice age
      - tectonic movement
    Soon our impact will be superior to the asteroid that extinted dinosaurs
**** Anthropocene
:PROPERTIES:
:NOTER_PAGE: (9 . 7486)
:END:
    The epoch of the Sapiens -- Holocene
    Sapiens broke the barrier between the biomes
    - they united the globe into one ecological unit for the first time
      - they shuffled species all around the world

**** Animism
:PROPERTIES:
:NOTER_PAGE: (9 . 8741)
:END:
It is believe the first humans considered animals and plants and spirits to be inihabitants of the same land as themselves
- all beings were considered at the same level

This view is now alien to nearly everyone


***** Serpent
:PROPERTIES:
:NOTER_PAGE: (9 . 10373)
:END:
- even the Bible were created much later than that time:
  - the sole occurrence when an animal initiates conversation is the serpent in the garden of Eden
    - a _condamnation of Animism_
Adam and Eve lived as forangers
- expulsion from Eden == Agricultural Revolution
- Eve means snake in most Semitic Languages

An archaic animistic mith believed humans descended from priomordial snakes or lizards
- this is believed by modern Westeners
  + the human brain is built around a reptillian core

_In the Genesis_
- everything is initiated by God in the first part
- then the serpent initiates conversation
  + this is followed by the first act initiated by Eva that responds
This is the series of events that lead to the fall from grace



***** Ancestral Needs
:PROPERTIES:
:NOTER_PAGE: (9 . 14517)
:END:

_Agricultural Revolution_
- by-products
  + Bible
  + Domesticated animals
    - they suffer greatly although still living on and multiplying
      + the humans needs shape their life and their emotional needs are ignored
        - as these needs were formed milions of years ago these animals suffer greatly as a resoult of not meeting them, even if from a evolutional standpoint they don't need to anymore

_Algorithms_
- these algorithms take in sensual input and output sensations and feelings
- all animals live guided by algorithms that work on probabilities
  + to get eaten
  + to feed
  + to reproduce
  + Humans are complex algorithms
    - they produce copies of themselves
  + All animals are
    - these algorithms are always undergoing a quality control in the form o natural selection

_Theist Religions_
- catered to peasants and shepards
  + their holydays revolved around farming

***** Agricultural deal
:PROPERTIES:
:NOTER_PAGE: (9 . 42346)
:END:

- in the animistic cosmos everybody interacted directily with one another
- in the theist cosmos the Gods mediate
  + non-human entities are silenced
    - this serves the two main parties at the expense of the ecosystem

Jainism, Buddhism and Hinduism demonstrate more empathy toward animals
- ~Ahimsa~ - non-violence
  + this extends to all living being, not only humans as in the Bible

Still, in all religions humans are placed higher on some sort of hierarchy
- The Deal
  + cosmic forces grant humankid command over other animals on some condition toward the Gods, Nature, the animals themselves


****** Hunters vs Farmers
:PROPERTIES:
:NOTER_PAGE: (9 . 48882)
:END:
- hunters
  + were in smaller number than the animals they hunted
  + were in contact with the animals and their behavior and thinking
- farmers
  + lived in a world controlled by human dreams and ideas
  + lived with domestic, subjogated animals

***** One Man Show
:PROPERTIES:
:NOTER_PAGE: (9 . 51824)
:END:
If with the Agricultural Revolution humans sileced Nature;
With the scientific revolution they silenced God
- Humankind stood on an empty stage

****** Newton's Tree of Knowledge
:PROPERTIES:
:NOTER_PAGE: (9 . 53019)
:END:
The story turns the Genesis on its head
- man is now the sole agent
  + not at the mercy of the Serpent or God anymore

****** Humanist Religions
:PROPERTIES:
:NOTER_PAGE: (9 . 55283)
:END:
Risen with the scientific revolution, worship of humans
- Founding ideas
  - good or bad in the cosmos is judged according to its impact on Homo sapiens
  - Homo sapiens has sacred essence of meaning and authority on the universe
- Example of humanist religions
  - liberalism
  - communism
  - Nazism

****** Rethinking of lower life-forms
:PROPERTIES:
:NOTER_PAGE: (9 . 57271)
:END:
In the recent years this is a trend
Maybe because we are about to become a lower life-form ourselves with AI super-intelligence
- if AI should not be allowed to exploit humans for its ends why should humans be allowed to do so with nature?


*** Spark
:PROPERTIES:
:NOTER_PAGE: (10 . 646)
:END:




* The Meaning


* The Control
