:PROPERTIES:
:ID:       993bbd99-1094-42bc-98bf-3eeeba0c4d9f
:END:
#+title: BD Vaccini
[[id:96d0a247-0c7c-40c2-bd29-e514a2d93502][$project]]
[[id:f956b52b-6fe3-4040-94e5-7474d1813a38][#university]]

* Progettazione Concettuale

** Requisiti Iniziali
Si vuole realizzare una base di dati per la gestione di una campagna vaccinale su scala
nazionale in risposta alla recente epidemia di COVID19 che ha colpito il Paese.

Ogni cittadino è un potenziale vaccinando di cui sono noti nome, cognome, età, città ed indirizzo di residenza, codice fiscale.
I cittadini sono ulteriormente suddivisibili secondo l'occupazione in personale sanitario e scolastico, categorie fragili (es, soggetti immunodepressi) e altri.

Sono disponibili tre tipi di vaccino: COVIDIN, CORONAX e FLUSTOP.
Ogni vaccino ha un'età minima e massima di somministrazione e una certa efficacia.
Ogni vaccino può richiedere una (FLUSTOP) o due (COVIDIN, CORONAX) somministrazioni. Nel caso siano necessarie due somministrazioni, l'intervallo temporale minimo tra prima e seconda dose varia da vaccino a vaccino.
Ogni vaccino è organizzato in lotti con data di produzione e scadenza. Di ogni lotto si conoscono le reazioni allergiche eventualmente riscontrate nel Paese.

I centri vaccinali sono distribuiti nelle varie città del Paese a diversi indirizzi e possono esserci più centri per ogni città;
ogni centro vaccinale dispone in ogni momento di zero o più fiale di uno o più vaccini ed a ogni centro afferiscono uno o più medici.

Ogni cittadino può fare richiesta di vaccinazione prenotando tramite un sito web o una app per smartphone (Figura 1), lasciando anche un recapito per essere ricontattati. Nel caso del sito web, é richiesto un indirizzo email al posto del numero di cellulare.

Una task force di operatori riceve le richieste di vaccinazione ed organizza un appuntamento vaccinale come segue.
Ogni cittadino vaccinando può essere indirizzato esclusivamente ad un centro localizzato nella città di residenza.
Personale sanitario e personale scolastico possono accedere ai vaccini COVIDIN e CORONAX.
I soggetti fragili possono accedere solo a CORONAX e FLUSTOP.
Gli altri soggetti non possono accedere a CORONAX.

Nel caso il cittadino abbia avuto precedenti reazioni allergiche, non può essere raccomandato nessun vaccino per cui almeno un lotto abbia registrato una segnalazione di reazione avversa negli ultimi 30 giorni.
Il cittadino viene indirizzato al centro più vicino alla residenza dove vi sia disponibilità di almeno una fiala di vaccino compatibile con i vincoli sopra.
Nel caso in cui il vaccinando abbia positività pregressa ad un test COVID, viene specificato che la seconda dose del vaccino, se prevista, non deve essere somministrata.
La persona riceve una convocazione al contatto indicato contenente data, ora, centro di vaccinazione, tipo di vaccino da somministrare.
Il cittadino vaccinando, munito di convocazione, si reca in data indicata al centro vaccinale indicato.

Ogni medico è identificato tramite i medesimi dati registrati per i cittadini, e l’afferenza ad un particolare centro vaccinale.
I medici si suddividono in medici di base e altri, dove i primi possono somministrare solo vaccini a doppia dose, mentre i secondi sono abilitati anche alla somministrazione di vaccini a singola dose.
Al momento dell’arrivo del vaccinando al centro, un medico fra quelli abilitati a somministrare il vaccino richiesto si prende in carico il vaccinando.

In seguito ad ogni vaccinazione, il medico tiene il vaccinato sotto osservazione per 15 minuti per monitorare eventuali effetti allergici relativamente al particolare lotto di vaccino utilizzato.
Se non si verificano particolari effetti avversi e il vaccino richiede un richiamo ed il soggetto non ha pregressi di positività COVID, il medico aggiorna la convocazione con un secondo appuntamento per la somministrazione presso la stessa sede dello stesso vaccino in data compatibile con le specifiche del vaccino.
Al contrario, se si verifica un effetto allergico, il medico emana un report che indica data e luogo della vaccinazione, tipo vaccino e numero lotto che hanno causato l’allergia al paziente in questione.
Il sistema deve permettere inoltre di eseguire le seguenti operazioni:
- Ogni sera viene stilato un rapporto che indica quante vaccinazioni sono state fatte nella giornata in tutti i centri vaccinali suddivise per categoria di cittadino.
- Ogni sera, ogni centro vaccinale fa l’inventario del numero di dosi ancora disponibili per ogni vaccino.
- Ogni fine settimana, viene stilato un report che indica quante vaccinazioni sono state fatte per ogni vaccino per ognuna delle categorie di cittadini e quante di queste

** Requisiti Rivisti

Si vuole realizzare una base di dati per la gestione di una campagna vaccinale su scala
nazionale in risposta alla recente epidemia di COVID19 che ha colpito il Paese.

Per i cittadini rappresentiamo nome, cognome, età, città, indirizzo di residenza, codice fiscale, numero di cellulare, email.
I cittadini possono essere personale sanitario, scolastico, categorie fragili (es. soggetti immunodepressi) e altri.

Per i vaccini rappresentiamo nome (COVIDIN, CORONAX e FLUSTOP), etá minima di somministrazione, etá massima di somministrazione, efficacia, numero di somministrazioni, intervallo tra dosi.

Per i lotti rappresentiamo il nome del vaccino, data di produzione, data di scadenza.

Per le reazioni allergiche rappresentiamo la reazione, il lotto, codice fiscale del cittadino.

Per i centri vaccinali rappresentiamo cittá, indirizzo.
Possono esserci più centri per ogni città.
Ogni centro vaccinale dispone in ogni momento di zero o più fiale di uno o più vaccini.
Ad ogni centro vaccinale afferiscono uno o più medici.

Per i medici rappresentiamo nome, cognome, etá, cittá, indirizzo di residenza, codice fiscale, centro vaccinale.
Ogni medico afferisce ad un particolare centro vaccinale.
I medici si suddividono in medici di base e altri.

Ogni cittadino può fare richiesta di vaccinazione prenotando tramite un sito web o una app per smartphone (Figura 1), lasciando anche un recapito per essere ricontattati. Nel caso del sito web, é richiesto un indirizzo email al posto del numero di cellulare.

Una task force di operatori riceve le richieste di vaccinazione ed organizza un appuntamento vaccinale come segue.
Ogni cittadino vaccinando può essere indirizzato esclusivamente ad un centro localizzato nella città di residenza.
Personale sanitario e personale scolastico possono accedere ai vaccini COVIDIN e CORONAX.
I soggetti fragili possono accedere solo a CORONAX e FLUSTOP.
Gli altri soggetti non possono accedere a CORONAX.

Nel caso il cittadino abbia avuto precedenti reazioni allergiche, non può essere raccomandato nessun vaccino per cui almeno un lotto abbia registrato una segnalazione di reazione avversa negli ultimi 30 giorni.
Il cittadino viene indirizzato al centro più vicino alla residenza dove vi sia disponibilità di almeno una fiala di vaccino compatibile con i vincoli sopra.
Nel caso in cui il vaccinando abbia positività pregressa ad un test COVID, viene specificato che la seconda dose del vaccino, se prevista, non deve essere somministrata.

La persona riceve una convocazione al contatto indicato contenente data, ora, centro di vaccinazione, tipo di vaccino da somministrare.
Il cittadino vaccinando, munito di convocazione, si reca in data indicata al centro vaccinale indicato.
Al momento dell’arrivo del vaccinando al centro, un medico fra quelli abilitati a somministrare il vaccino richiesto si prende in carico il vaccinando.
I medici di base possono somministrare solo vaccini a doppia dose, mentre gli altri sono abilitati anche alla somministrazione di vaccini a singola dose

*** Glossario dei termini
| termine            | descrizione                                  | sinonimi             | collegamenti         |
|--------------------+----------------------------------------------+----------------------+----------------------|
| cittadino          | persona residente in Italia, puó essere      | vaccinando, persona, | vaccini, cittá       |
|                    | personale sanitario, scolastico, altro       | paziente, soggetto   | reazioni             |
|--------------------+----------------------------------------------+----------------------+----------------------|
| medico             | di base o altri, afferiscono ad un centro,   |                      | centro, cittá        |
|                    | amministrano le dosi dei vaccini             |                      |                      |
|--------------------+----------------------------------------------+----------------------+----------------------|
| vaccinazione       | di un cittadino con un vaccino specifico,    |                      | cittadino,           |
|                    | con richiamo se necessario                   |                      | vaccino              |
|--------------------+----------------------------------------------+----------------------+----------------------|
| vaccino            | COVIDIN, CORONAX o FLUSTOP                   |                      | vaccinazione         |
|--------------------+----------------------------------------------+----------------------+----------------------|
| lotto              | unitá organizzativa di un vaccino,           |                      | reazioni allergiche, |
|                    | ha una data di produzione e scadenza,        |                      | vaccino              |
|--------------------+----------------------------------------------+----------------------+----------------------|
| reazione allergica | reazioni riscontrate in Italia,              | reazione avversa,    | cittadino, lotto     |
|                    | da un cittadino verso un lotto               | effetti avversi,     |                      |
|                    |                                              | allergia             |                      |
|--------------------+----------------------------------------------+----------------------+----------------------|
| centro vaccinale   | centro in cui i cittadini possono vaccinarsi | centro               | cittá                |
|--------------------+----------------------------------------------+----------------------+----------------------|
| cittá              | in cui si trovano i centri vaccinali         | residenza            | centro vaccinale,    |
|                    |                                              |                      | cittadino            |
|--------------------+----------------------------------------------+----------------------+----------------------|
| fiala              | singola dose di vaccino                      | dose                 | lotto, vaccino,      |
|                    |                                              |                      | centro vaccinale     |
|--------------------+----------------------------------------------+----------------------+----------------------|

*** Operazioni

** Schema ER Iniziale
[[https://erdplus.com/edit-diagram/95b219b3-3c04-46d2-bc6e-4bc802c5b98b][link]]

** Business Rules
- Un cittadino puó accedere solo a centri vaccinali della propria cittá di residenza
- Un cittadino per un dato Vaccino deve  al massimo avere confermato $n$ appuntamenti con $n$ uguale al Numero Somministrazioni del Vaccino
- Un Cittadino per poter ricevere un Vaccino deve avere Etá compresa tra le etá minima e massima di somministrazione
- Un Cittadino:
  + fragile, CORONAX, FLUSTOP
  + personale sanitario, COVIDIN, CORONAX
  + personale scolastico, COVIDIN, CORONAX
  + nessuno dei precedenti, CORONAX
- Un cittadino che ha riscontrato reazioni avverse non puó accedere a dosi il
  cui lotto ha riscostrato almeno una reazione avversa negli ultimi 30 giorni
- Un cittadino con positivitá pregressa non deve ricevere seconda dose se specificata
- Medici base somministrano solo vaccini a doppia dose

** Schema + BR

* Progettazione Logica

** Tavola dei Volumi

** Tavola delle Operazioni

** Analisi delle Ridondanze

** Schema ER Ristrutturato + BR

** Schema Relazionale
