:PROPERTIES:
:ID:       95e51b2a-a53a-42a9-b585-a2f62d989828
:END:
#+title: Dalla Robotopia al Cyberpunk
- Source: https://not.neroeditions.com/dalla-robotopia-al-cyberpunk/

  #+begin_quote
  Perché il Giappone appare, perennemente, come la più intrinsecamente futuristica tra le nazioni? Quando ero bambino il futuro era l’America. Il ruolo del Giappone stava solo nella produzione di robot di latta a carica e astronauti di plastica stampati a iniezione. Quarant’anni dopo, la relazione speciale che l’America aveva con il futuro si è spezzata.
  ~ [[id:7a2841f8-6093-4aac-8834-13b4d00a1e5b][William Gibson]]
  #+end_quote

- Giappone - Tecnologia
  + Epoca Meiji
    * 1868 - 1912
    * acquisire tecnologie aliene per sopravvivere
  + Seconda guerra mondiale
    * bomba atomica massima espressione della scienza occidentale
    * vera apocalisse
  + Dopoguerra
    * tecnologia e societa' dei consumi creano a identita' nazionale odierna
- [[id:4ae3eed0-e31b-4e2b-a898-2883b06b6bb9][Nishida Kitaro]]
  + fondatore della scuola di Kyoto
    * /filosofi del nulla/
  + compremesso cultura giapponese e tecnologia occidentale
    * *Mondo Storico* condizione ideale, dissolvere l'opposizione Est-Ovest in un'unicita' universale senza perdere le proprie particolarita'
* Robot
- fumetto esprime fantasie, speranze e dubbi riguardo il nuovo mondo
  + Kasei Tanken - 1940
  + Kagaku senshi - 1943
  + Tetsuwan Atom - 1950
    * Astro Boy, [[id:1ee42655-3289-4a7a-941f-f0bf8ff547be][automa]] e non telecomandato, parte del successo
- generalizzando aspetti dello shintoismo
  + /ogni cosa e' sacra e ha uno spirito/
    * /kami/ in ogni dove
  + il robot e' visto come vivo

Queste letture sono culla di autori come [[id:ec867e33-0be2-4fb2-9ebe-f337e4b614df][Masamune Shiro]] (/Ghost in the Shell/).
- un infanzia educata dalla _fanta robotica_
- robot amici, attrezzi umani
- tecnologia nel dopoguerra fondamentale per la ricostruzione e per l'emancipazione dal'occidente e la colonializzazione

- Mecha - primi anni '70
  + Mazinga Z
  + UFO Robo

Il genere fantascientifico in Giappone e' frutto di molte influenze conteporanee dal occidente.
Nel 1973 con /Gundam/, Tomino Yashiyuki, si passa dal /super robot/ al /real robot/
- l'elemento robotico viene considerato arma militare e trattata da tale
- da qui nasce anche un certo feticismo militaresco
  + [[id:c3792673-2478-45db-990f-7bdf76862491][Metal Gear Saga]]

* Innesti
- meta' anni '80
  + /Akira/ - Otomo Katsuhiro
  + /Neuromante/, non tradotto in giapponese
- /Ghost in the Shell/ - Shirow Masamune
  + lungometraggio, elementi cyberpunk accessori estetici
  + manga, densi di cibernetica applicata, implecazioni etiche discusse nelle note dell'autore
- /Anita/ - Kishiro Yukito
  + piu' legato alla parte organica

Tra '80 e '90 emerge la figura del cyborg femminile, in contraltare coi i corrispettivi occidentali
- /Cyborg Manifesto/, Donna Haraway

Queste opere sono sintomo del conflitto giapponese
- io / altro
- organico / inorganico
- Giappone / Occidente

#+begin_quote
Alita, eroina senza memoria alla ricerca della propria identità, riproduce inconsciamente il percorso che fu del Giappone sulla scena mondiale tra l’era Meiji e la fine del XX secolo. È in successione ‘aggressore dei propri vicini’ (cacciatrice di taglie), ‘vincitrice di una competizione economica’ (campionessa sportiva) e ‘alleata degli Stati Uniti’ (mercenaria per Salem) prima di scoprire che un tempo fu Yoko (giapponese, dunque), guerriera sconfitta e decapitata.
~ Bouissou
#+end_quote

* Superflat
- /A Theory of Super Flat Japanese Art/ - Murakami Takashi
- convenzioni pittoriche tradizionali dell'antico Giappone
  + spazio piano
  + poca profondita' negli spazi e nei volti
  + presenti fortemente nell'arte popolare di manga anime videogiochi

- /Neon Genesis Evangelion/ - 1995
  + ultima evoluzione del Mecha
  + rivolto al publico /Otaku/, con il canale diretto del merchandise

- Otaku, evasione dalla realta'
  + eversione e ribellione dalla realta' ultra-tecnoliberista da una severissima morale sociale
  + misero paliativo che cementifica la realta' prigione
  + in questo senso l'erotizzazione: _ribaltamento della norma e catarsi_

* Nichilismo
- /Blame!/ - Tsutomu Nihei
  + iperoggetti, [[id:0792e071-3ac6-4301-a2d3-740a0b162e29][Timothy Morton]]
  + incubi tecnologici, [[id:04a74d3b-7659-4fb8-b939-253f854cb344][Nick Bostrom]]
