:PROPERTIES:
:ID:       126edf30-7ebf-4d54-9607-8dea48e478ce
:END:
#+title: Beware The Man Of One Study
#+date: [2022-12-07 Wed 02:14]
#+filetags: article
- Source: https://slatestarcodex.com/2014/12/12/beware-the-man-of-one-study/
- Author: [[id:c0fd7c38-2a33-4988-9f43-6eee6dca1666][Slate Star Codex]]
- Related: [[id:03d58ce6-d9d0-4955-b4c6-6821a5a14216][The Cowpox of Doubt]], [[id:3f9e8e01-bcc3-4bf0-8b74-13f1cb600472][Research]], [[id:2218c0bd-2e5f-46d1-bcd0-313bbe02cec3][Cherry Picking]], [[id:8d0d9ade-f935-4def-ba51-1af627003f3c][Skepticism]]

* Notes
#+begin_quote
But there are also about 5 studies that find that the drug is very good, and 5 studies missing the sign entirely and finding that the drug is actively bad. There’s even 1 study finding that the drug is very bad, maybe seriously dangerous.

This is before we get into fraud or statistical malpractice. I’m saying this is what’s going to happen just by normal variation in experimental design. As we increase experimental rigor, the bell curve might get squashed horizontally, but there will still be a bell curve.

In practice it’s worse than this, because this is assuming everyone is investigating exactly the same question.
#+end_quote
- a *well covered* topic of research /will/ have data for and against it
  - malpractice
  - /slightly/ different premise
  - statistical variation
- this means there will always (probably) be papers to be cherry picked

Research is complicated, on the surface opposite thesis can be reputable in the same way (especially politics):
#+begin_quote
Economic theory has always shown that minimum wage increases decrease employment, but the Left has never been willing to accept this basic fact. In 1992, they trumpeted a single study by Card and Krueger that purported to show no negative effects from a minimum wage increase. This study was immediately debunked and found to be based on statistical malpractice and “massaging the numbers”. Since then, dozens of studies have come out confirming what we knew all along – that a high minimum wage is economic suicide. Systematic reviews and meta-analyses (Neumark 2006, Boockman 2010) consistently show that an overwhelming majority of the research agrees on this fact – as do 73% of economists. That’s why five hundred top economists recently signed a letter urging policy makers not to buy into discredited liberal minimum wage theories. Instead of listening to starry-eyed liberal woo, listen to the empirical evidence and an overwhelming majority of economists and oppose a raise in the minimum wage.
#+end_quote

and

#+begin_quote
People used to believe that the minimum wage decreased unemployment. But Card and Krueger’s famous 1992 study exploded that conventional wisdom. Since then, the results have been replicated over fifty times, and further meta-analyses (Card and Krueger 1995, Dube 2010) have found no evidence of any effect. Leading economists agree by a 4 to 1 margin that the benefits of raising the minimum wage outweigh the costs, and that’s why more than 600 of them have signed a petition telling the government to do exactly that. Instead of listening to conservative scare tactics based on long-debunked theories, listen to the empirical evidence and the overwhelming majority of economists and support a raise in the minimum wage.
#+end_quote

Who is right?
- meta-analysis can be helpful or equally confusing
- author in the article uses a funnel plot to meta-analyze
