:PROPERTIES:
:ID:       7fd778d4-8ce4-403d-91a1-a558ebc7fb0b
:END:
#+title: Death is Nothing at All
#+date: [2022-01-04 Tue 00:52]
#+filetags: poem literature
Poem on [[id:c22ecc22-6b58-45f2-a35b-3b75e1d4f5e8][Death]] by [[id:41ec59d1-ac07-41d1-82dd-f98906e5d493][Henry Scott-Holland]]
#+begin_quote
Death is nothing at all.
It does not count.
I have only slipped away into the next room.

Nothing has happened.
Everything remains exactly as it was.
I am I, and you are you, and the old life that we lived so fondly together is untouched, unchanged.
Whatever we were to each other, that we are still.

Call me by the old familiar name.
Speak of me in the easy way which you always used.
Put no difference into your tone.
Wear no forced air of solemnity or sorrow.

Laugh as we always laughed at the little jokes that we enjoyed together.
Play, smile, think of me, pray for me.
Let my name be ever the household word that it always was.
Let it be spoken without an effort, without the ghost of a shadow upon it.

Life means all that it ever meant.
It is the same as it ever was.
There is absolute and unbroken continuity.
What is this death but a negligible accident?

Why should I be out of mind because I am out of sight?
I am but waiting for you, for an interval,
somewhere very near,
just round the corner.

All is well.
Nothing is hurt; nothing is lost.
One brief moment and all will be as it was before.
How we shall laugh at the trouble of parting when we meet again!
#+end_quote
