#+TITLE:  Economia e Diritto
#+ROAM-ALIAS: EGID
#+Teacher: Camillo Sacchetto, Fabio Montalcino, Valentina Cillo
[[file:#university.org][#university]]

* Economia
(25/30 di scritto + esercitazioni)
** Business Model Canvas
Modello economico sostenibile
- backend - frontend
  + condividono la Value Proposition
    - risoluzione di un problema
    - ti do l'opportunita' di fare qualcosa che prima non facevi
- Customer Segments
- Channels

*** Customer Segments
gruppi di persone o organizzazione che la azienda mira a raggiungere, fornire
- bisogni comuni
- comportamenti comuni
- altri attributi

Le aziende devono fare scelte coscienziose per quanto riguarda che aree servire e che aree ignorare
- deve esserci una forte comprensione dei bisogni dei clienti
Divisioni
- bisogni
- canali di distribuzione
- tipi di relazione
- profittabilita'
- aspetti dell'offerta
Q:
- per chi creo valore
- chi sono i nostri clienti piu' importanti

Segmenti
- mass market
  + il business model non distingue tra customer segments
  + i canali e le relazioni si concetrano su un largo gruppo di clienti
- niche market
  + Specifico e specializzato
  + spesso tratta relazioni tra fornitore-compratore
- segmentato
  + prodotto simile ma offerto a diversi gruppi
- diversificato
  + segmenti diversi e prodotti diversi
- multi-piattoforma
  + permettono l'incontro tra offerta e domanda
  + non forniscono nulla di reale se non la piattaforma
*** Value Proposition
Tutta la struttura dovra' essere compatibile con questa sezione
- Qual'e' lo scopo del prodotto e i suoi usi
- A chi e' mirato questo prodotto, dove si collocano
  + decisori o utenti, clienti (e' disponto a riconoscere un valore non necessariamente monetario)
  + che prodotto indiriziamo ad ogni segmento di clientela
    - Valori diversi
      + quantitativo
        - prezzo
        - velocita' di consegna
      + qualitativo
        - design
        - esperienza cliente
- Che bisogni soddisfa il prodotto
  + che problema risolve
- Come trasferisco il prodotto al cliente
- Qual'e' il posizionamento del prodotto, definizione del prezzo

Elementi
- novita'
- performance
- custom
- ti consento di fare meglio il tuo lavoro
- Design
- Brand/Status
- prezzo
  + scelta in base all'aspettativa delle clientela
- aumento del margine di guadagno per i clienti
- riduzione del rischio
- accessibilita'
  + a servizi non normalmente accedibili
- convenienza/usabilita'

*** Channels
Strumenti fisici o virtuali che permettono di raggiungere i segmenti di mercato
I canali sono insiemi di strumenti con cui l'azienda consegna la Value Proposition ai clienti
- *Funzioni*
  + Rendere a conoscenza dell'offerta dell'azienda il cliente
  + Consentire una valutazione della value proposition corretta da parte del cliente
  + Permettere l'acquisto del prodotto
  + Trasferire materialmente o meno il prodotto
  + Assicurare supporto al cliente (assistenza)

Da considerare l'efficienza dei canali e della loro integrazione reciproca
anche rispetto a canali diretti e indiretti, piú il cliente finale é lontano piú sará difficile analizzarlo.

*** Customer Relationships
Spesso sono bidirezionali
- 3 *obiettivi*
  + Acquisizione di nuovi target, aumento della base di clientela
  + Mantenimento della base di clientela
  + Aumento della vendita, upselling e cross-selling

Le diverse modalitá devono essere integrate, non devono creare confusione nel cliente: in questo caso é alto il rischio di perdita del cliente.

- *Modalitá*
  + Assistenza personale
  + Assistenza personale dedicata, molto piú costruito sulle singole esigenze
  + Self-service
  + Servizi automatizzati
  + Comunitá
    - acquisti di gruppo
  + Co-creazione
    - Kickstarter, Youtube, Amazon

*** Revenue Streams
L'utile o margine netto che si ricava
- transazioni unica una tantum di un cliente
- transazioni ricorrenti

Domanda importante: a cosa il cliente é disposto a riconoscere un valore
- ci sono diversi modi per generare _revenue stream_
- ció che conta é la somma complessiva dei R.S.

Modalitá
- venditá di asset
- pagamento in base all'uso
- pagamento ad iscrizione
- affitto/leasing/prestito
- pagamento di licenza
  + uso di prodotti ~intangible~
- brokeraggio
- pubblicitá
Meccanismi di definizioni del Prezzo
- fisso
- dinamico
  + in base al momento, al metodo di acquisto, il prezza cambia
  + negoziazione
  + al momento in base a domanda e offerta

*** Resources
Gli asset che permettono di non venir meno alla Value Proposition
Le risorse si dividono in:
- fisiche - tangibili
- finanziarie
  - vantaggio nel trasferimento della risorsa
- intellettuale
- umane
Ulteriormente divise in:
- proprietarie o gestite dall'azienda
- acquisiti da partner
Quest'ultima distinzione non importa molto dal punto di vista della Value Proposition

** Contesto Socio Economico dell'impresa
*** Ambiente di riferimento
tutto ció che puó direttamente e indirettamente influire sulla crescita e dinamica dell'impresa
Include:
- vincoli e opportunitá
- minacce, convenienze
- specifico e generale
Puó essere:
- competitivo
- socio culturale
- ecosistema (fisico - naturale)

=DEF= Mercato
In termini economici, si ha un mercato in tutti i casi in cui vi siano due o piú contraenti disposti a scambiare tra di loro i beni rispettivamente posseduti

Impresa e Ambiente
- si scambiano risorse
  - scambi in entrata
    + acquisizione degli input
  - scambi in uscita
    + cessione dell'output
- si influenzano
- =macroambiente=
  + rischi e opportunitá provengono da qui
  + sistema delle condizioni e dei vincoli in cui si verificano gli scambi
    - Sistema politico-istituzionale
    - Sistema culturale tecnologico
    - Sistema economico
    - Sistema socio-demografico
  + l'impresa non puó condizionare il macroambiente
- =microambiente=
  + mercati con cui l'impresa scambia in entrata ed uscita
    - ambiente transazionale
      + mercato del lavoro
      + mercado di produzione
      + mercado finanziario
    - ambiente competitivo
      + clienti serviti
      + imprese concorrenti
  + l'impresa puó condizionare il microambiente

- =outcome=
  + impotto sull'utenza con il mio output
  + misurato con la soddisfazione del mercato di riferimento

*** L'Industria 4.0
1. Meccanizzazione, macchina a vapore ~1784~
2. Produzione di massa, elettricitá ~1870~
3. Automazione, computer, elettronica ~1969~
4. Robotica, intenet delle cose, reti ~oggi~

Per ogni industria ci sono delle tecnologie abilitanti
Per la 4.0
- robotica
- stampanti 3d
- realtá aumentata
- simulazione
- integrazione verticale o orizzontale
- internet
- cloud
- big data
- cyber-security

*** Impresa
organizzazione economica che svolge processi di acquisizione e di prodzione di beni o servizi
Attivitá economica organizzata dall'imprenditore al fine della produzione e dello scambio di beni o di servizi

Puó essere considerata un sistema socio-tecnico
- sociale: il suo andamento é condizionato dall'ambiente sociale
- tecnico: il suo funzionamento necessita di strumenti che incorporano tecnologie
- aperto: l'ambiente esterno influenza l'andamento dell'impresa: é anche dinamico in quanto deve adattarsi all'esterno

Funzioni Istituzionali:
- organizazione economica
- sistema sociale
- struttura patrimoniale

Teorie sulle finalitá
- massimizzazione del profitto
- sopravvivenza dell'impresa
- creazione e diffusione del valore economico
- sviluppo dimensionale
- massimizzazione sociale del profitto
- conseguimento del successo sociale
  + reddito
  + potere
  + posizione sociale

Forme istituzionali
- capitalistica
- manageriale
- cooperativa
- non profit
- post-manageriale
Grado di controllo dell'imprenditore varia
- assoluto
- familiare
- coalizione
- supervisione finanziaria
- public company
Ragione Sociale
- forme individuali
- forme collettive

- Gestione
  + Strategica
  + Direzionale
  + Operativa

- Stakeholder, Portatori di interesse
  + primari
  + secondari
  + supportive
  + non supportive
  + mixed
  + marginali
- Joint venture
  + rapporti strategici con stakeholder
  + con concorrenti

*** Catene del Valore

Progettazione -> Produzione -> Logistica ->
Marketing(in e out) -> Servizio clienti -> Gestione delle risorse(umane, tecnologiche)

Le scelte di make/buy vengono fatte con studi su conti/benefici

Dipende dal tipo di attivitá, dal suo tipo, dal suo ciclo vitale
- insieme delle attivitá primarie
  + che seguono il percorso del cliente
Evidenzia insiemi di attivitá interdipendenti
- legate in termini di risorse allocate e di competenze necessarie
  + orizzontali
    - collegamenti tra Produzione e Servizi per esempio
      + attivitá di manutenzione e conti degli interventi in garanzia
  + verticali
    - tra attivitá di supporto e primarie
      + collaborazione tra risorse umane, sviluppo di tecnologia,approvvigionamento con la Produzione(e le attivitá base primarie)

I collegamenti vanno considerati per ottenere un vantaggio competitivo
- ottimizzazione
  + trade-off tra le attivitá
- coordinamento
  + spesso riduce i costi o enfatizza la differenziazione
    - prodotto generico / costi minori
    - prodotto unico / conto maggiore
Quindi vantaggi:
- di costo
- di differenziazione
  + prestazione
  + caratteristiche
  + el. complementari
    - assistenza
    - consegna
    - disponibilitá

Strategie:
- strategie di costo
- strategie di differenziazione
  + modificare caratteristiche fisiche, tecniche, estetiche o psicologiche associate al prodotto
- strategie di focalizzazione
  + la differenza sta nell'area di mercato, delle nicchie

**** VRIO
- Valore
- Raritá
- Imitabile
- Caratteristico nella Organizzazione
- Implicazioni competitive
- Performance

* Diritto
Esistono diverse fonti di Diritto
- nazionali
  + sentenze
  + DPCM
  + DPC
- internazionali

Esistono conflitti di fonti
- nazionali | comunitarie
- gerarchia delle fonti

Definizione dei soggetti
- giuridica
  + aggiunge sfumature
- tecnica

Quando si regolamenta - tecnica linguistica:
1. tecnica analitica
   - disciplinare soggetti utilizzando un elenco analitico ricade nella regolamentazione
     + cio' che non e' citato rimane non disciplinato, allora va estesa eventualmente per analogia
   - vietata nel diritto penale italiano
2. tecnica per principi
   - si mantiene una generalita'
   - va sempre fatto un passaggio logico quando questa e'
applicata
   - e' facilmente ambigua

3. Settori
   - civile
   - penale
   - amministrativo
   - del lavoro

** Responsabilita' ISP
Tematica sorta nei primi anni 2000
Scelta della *fonte*
- Direttiva Comunitaria 2000/31 (!Regolamento Comunitario)
  + commissione europea
    - da' dei parametri a tutti i paesi membri
    - che dovranno essere applicati dai singoli paesi
      + se non in linea potranno essere disapplicati
  + considerando che... n.42
    - il processo tecnico di attivare e fornire accesso ad una rete
    - l'attivita' e' meramente tecnica automatica e passivo
    - non conosce ne' controlla le informazioni
- Decreto Legislativo n.70 2003
*** Art. 17
1. assenza dell'obbligo generale di sorveglianza da parte del prestatore e di ricerca attiva
2. tenuto ad
  a. informare l'autorita' qualora sia a conoscenza di attivita' o informazioni illecite riguardanti un suo destinatario
  b. fornire a richiesta delle autorita' competenti le informazioni in suo possesso
3. prestatore civilmente responsabile del contenuto di tali servizi in caso non ha agito prontamente per impedire l'accesso a detto contenuto
  a. elemento integrativo da parte dell'Italia

*** Art. 14
Responsabilita' di Mere Conduit (semplice trasporto, Telecom)
1. colui che trasmette su una rete informazioni fornite da un destinatario o fronisce accesso alla rete, non e' responsabile delle informazioni trasmesse a condizione che
   a. non dia origine alla trasmissione
   b. non selezioni il destinatario della trasmissione
   c. non selezioni ne' modifichi le informazioni trasmesse
2. la memorizzazione automatica, intermedia e transitoria delle informazioni trasmesse deve servire solo alla trasmissione e la sua durata non deve eccedere il tempo ragionevolmente necessario a tale scopo
3. L'autorita' puo' esigere, anche in via d'urgenza, che il prestatore impedisca o ponga fine alle violazioni commesse

*** Art. 15
Responsabilita' nell'attivita' di memorizzazione temporanea (caching, Google)
1. il prestatore non e' responsabile della memorizzazione temporanea delle informazioni effettuata al solo scopo di rendere piu' efficace il successivo inoltro ad altri destinatari a loro richiesta
   a condizione che
   a. non modifiche tali info
   e. agisca prontamente per rimuovere le informazioni e senza indugio
2. L'autorita' puo' esigere, anche in via d'urgenza, che il prestatore impedisca o ponga fine alle violazione commesse
*** Art. 16
Responsabilita' nell'attivita' di memorizzazione di informazioni (hosting)
1. Memorizzazione di info fornite da un destinatario
   1) non sia a conoscenza del fatto che l'attivita' o l'informazione e' illecita
   2) *non appena* sia a conoscenza di tali fatti, *su comunicazione delle autorita'*, agisca immediatamente per rimuovere le informazioni o per disabilitarne l'accesso
      - aggiunta italiana, ha generato una ambiguita'
2. 1 non si applicano se il destinatario del servizio agisce sotto l'autorita' o il controllo del prestatore
3. L'autorita' puo' esigere, anche in via d'urgenza, che il prestatore impedisca o ponga fine alle violazione commesse

*** Art. 17 2019

*** Sentenze
**** Case history RTI
Gruppo Mediaset
- Febbraio 2010 - RTI | Youtube
  - diritto d'autore delle reti Mediaset
  - pone a carico del host provider l'obbligo di rimuovere immediatamente non appena avuto conoscenza di tale illiceita'
    + anche su comunicazione dal titolare dei diritti
  - Youtube non ha agito immediatamente
- Settembre 2011 - RTI | Yahoo!
  - l'inattivita' del prestatore di servizio, nonostante le segnalazioni delle presenza di numerosi contenuti in violazione dei diritti d'autore, lo renda colposamente responsabile
- Ottobre 2011 - RTI | Choopa , VVB
  + la non responsabilita' dell'hosting provider si ha purche' il prestatore del servizio non sia effettivamente a conoscenza dell'illiceita' o di fatti e circostanze che rendono manifesta detta illiceita'
  + ricorso respinto perche' RTI aveva inviato un'unica diffida senza una dettagilata e specifica indicazione dei video da rimuovere
  + non conta il paese in cui e' basato il provider, conta il luogo dove viene commesso l'illecito
    - RTI aveva visto lesi i suoi diritti nell'area del mercato italiana, quindi
**** Case history Google
Gia' la commissione europea specificava gli stati potessero specificare leggi in tema di motore ricerche
- Maggio 2012 - Meneghetti | Google (utente anonimo)
  - in mancanza di un *ruolo "attivo" sulla conoscenza e controllo dei dati memorizzati* il motore di ricerca non e' responsabile dei contenuti immessi da terzi in rete, anche laddove gli stessi siano raggiungibili in quanto risultanti delle ricerche effettuate sullo stesso motore.
    + il mettere a disposizione non e' un ruolo attivo, in quanto inconoscibile
  - e' necessario che un organo giurisdizionale competente ne dichiari la effettiva illiceita' dei dati
- Febbraio 2013 - caso Vividown
  + video di violenze e insulti sulla piattaforma Google Video
  + Milano perche' sede Vividown
  + Google non responsabile del reato di diffamazione, in quanto rimosso appena segnalato
  + (primo grado) ma c'e' un trattamento illecito dei dati del ragazza disabile (dati sensibili) che non ha informato gli utenti della loro possibile responsabilita'
    - (secondo grado) ribaltata la responsabilita'
      + (cassazione) il decreto legislativo non si applica nel campo del diritto e alla riservatezza, Google ha fatto anche indicizzazione (azione attiva?) oltre che il mero upload
        - non c'e' trattamento illecito perche' *mancava della conoscenza dell'illecito,* anche avendo rimosso il contenuto collaborando con le autorita'
- Marzo 2009 - AVIS | SIXT, Google ADWords
  + concorrenza sleale, in quanto digitando AVIS si era reindirizzati
  + Comportamento abusivo del soggette che utilizzi come keyword segno distintivo altrui
    - la tecnica di marketing telematico ADWords, di per se, e' lecita
    - richieste di condanna respinte per carenza di legittimazione processuale (sarebbe dovuto essere Google Ireland)
- Marzo 2011 - | Google Autocomplete
  + ruolo attivo, evidente valenza diffamatoria
  + intervento sul software in modo da rimuovere l'associazione diffamatoria
- Maggio 2012 - | Google Autocomplete
  + Effetto del funzionamento del servizio completamente automatico, del tutto privo di valenza diffamatoria
  + non c'e' l'elemento del dolo, inoltre una azienda non ha una chiara componente psicologica
- Marzo 2013 - | Google Autocomplete
  + Secondo l'attore, Google e' un content provider, in quanto le funzioni di completamento automatico e di generazione di ricerche sono messe a punto dal provider
  + il Tribunale esclude la qualificazione di content provider
    - in quanto un sistema di attivazione del servizio e non certo di una funzione, ne' un contenuto
    - riproduce statisticamente il risultato delle ricerche piu' popolari
    - i risultati non costituiscono un archivio, ne' sono strutturati, organizzati o influenzati da Google
    - trattando di un Algoritmo non e' applicabile un Diritto prettamente umano
- Maggio 2013 - Reclamo al Collegio | Google Autocomplete
  + l'automatismo non e' sinonimo di neutralita' dell'ISP
  + nel suo ruolo svolge ulteriori attivita' non meramente automatiche e necessarie per la sola trasmissione o raccolta dei contenuti
  + inoltre l'elemento di lucro pone un ulteriore aspetto attivo da parte dell'azienda

**** Mediaset vs Facebook
=Roma, 20 Feb 2019=
Pagina facebook dedicata ad un cantone animato, con link a contenuti protetti da diritto d'autore.
Facebook non rimosse i contenuti, si passó al tribunale.
Caso storico per la presa di posizione nei confronti del Social Network
- definito come ISP
  + sia caching che hosting
- riconosce la responsabilitá del SN per violazioni avvenuti tramite ~linking~
  + quindi con pubblicazioni esterne alla piattaforma vera e propria
Focebook afferma la non correttezza del giudice, volendo il giudizio in California
- convenzione di Bruxelles '68 (principalmente tra paesi Europei, non USA)
  + cerca di chiarire dove va fatta la contestazione
- viene deciso che il mercato della parte lesa, luogo dell'evento in questione
  + Italia
Il link é una comunicazione al pubblico, l'articolo 13 della /riforma del diritto d'autore nel mercato unico digitale/ cita:
"I fornitori di servizi che fanno _comunicazione al pubblico_ devono ottenere l'autorizzazione per la messa a disposizione di contenuti dai titolari di diritti"
- qui c'é illecito nella non autorizzazione da parte di Mediaset, proprietaria dei diritti

**** Direttiva UE 2019/790
Del Parlamento Europeo e del Consiglio
=Direttiva Copyright=
In rif. al prestatore di un servizio dell'informazione... *va esclusa la responsabilitá prevista dall'art. 14 della direttiva 31/2000* ... dopo aver preso conoscenza, mediante informazione fornito dalla persona lesa o in altro modo, della natura illecita di quei dati o attivitá.
- se l'illiceitá é manifesto é obbligo del provider sospendere e rimuovere, se non manifesta va chiarita riferendosi, puó essere anche un elemento esterno a renderla manifesta
**** RTI vs Yahoo
=Corte di Cassazione, 19 Mar 2019=
Presunta violazione di diritti d'autore da parte di Yahoo
- DIFESA: la non immediata attivazione non implicava un illecito un quanto sito di Hosting Passivo
La giurisprudenza della Corte di giustizia ha accolto la nozione di hosting provider attivo riferendosi a prestatori che non conoscono né controllano le informazioni trasmesse o memorizzate dalle persone alle quali forniscono i loro servizi
- Cassazione: provider qualificabile come hosting attivo quando *completa e arricchisce* in modo non passivo *la fruizione dei contenuti*

Alla luce... l'hosting passivo é responsabile per non avere prevveduto all'immediata rimozione dei cantenuti illeciti o per aver continuato a pubblicarli

**** L'Oréal vs Ebay
- la disposizione della direttiva ~2000/31/CE art. 14~ deve essere interpretata non soltanto in considerazione del suo tenore letterale, ma anche del suo contesto e degli scopi perseguiti dalla normativa di cui essa fa parte

Sostanza sopra la forma

- Per quanto concerne l'art. 14 é necessario verificare se il prestatori di servizi svolge un ruolo attivo, anche ottimizzando la prestazione delle opere o altro materiale caricati o promuovenali, indipendentemente dalla naturo del mezzo utilizzato a tal fine.
  Dovrebbero adottare misure appropriate e proporzionate per garantire la protezione di tali opere a altro materiale, ad esempio tramite l'uso di tecnologie efficaci.
  - questo anche quando i prestatori di servizi rientrano nell'esenzione di responsabilitá di cui all' ~art. 14 della direttiva 2000/31/CE~

**** TikTok vs Garante Privacy
Gen 2021, strangolamento bambina di 10 anni a seguito della Blackout Challenge
- Fonti
  - Regolamento UE 2016/679
    - in vigore dal 2018
  - Decreto Legislativo 101/2018

Giá a dicembre il Garante della Privacy aveva sollevato delle contestazioni a TikTok
- Divieto di iscrizione ai piú piccoli facilmente aggirabile
- Scarsa tutela dei minori
- Poca trasparenza nelle informazioni resa agli utenti
- Impostazioni predefinite non rispettose della privacy
  - profilo pubblico di default

 Il limite d'etá prima del regolamento prevedeva 13 anni, questo per la legge federale USA:
 COPPA, prescrive che nessuno persona giuridica puó raccogliere dati relativi a minori di 13 anni
 In Italia il limite é definito a 14 anni.

 *Art. 66* procedura d'urgenza
 - per proteggere i diritti e le libertá degli interessati, un'autoritá, puó adottare immediatamente misure provvisorie intese a predurre effetti giuridici nel proprio territorio
   - periodo di validitá determinato che non supera i tre mesi

 Provvedimento dispone la misura della ~limitazione provvisoria~ del trattamento, vietando l'ulteriore trattamente doi dati degli utenti che si trovano sul territorio italiano per i quali non vi sia assoluta certezza dell'etá
 - prima ancora di sentire la controparte, ma ha giá valore di legge

TikTok si é impegnato ad adeguarsi alle richieste del Garante privacy
- blocco degli utenti per la richiesta di inserimento dell'etá
- miglioramento della propria informativa privacy in un linguaggio anch piú accessibile
- introduzione di report di utenti minori dei 14 anni
- banner di informazione sull'impostazione del profilo da pubblico a privato
Il garante ha avviato una collaborazione con il telefono Azzurro
- campagna di sensibilizzazione con l'obiettivo di richiamare i genitori a svolgere un ruolo attivo di vigilanza

** Principio di legalitá
3 presupposti
- riserva di legge
  + solo il potere legislativo, espressione del paese, ha manopolio normativo in materia penale
- tassativitá
  + tecnica di legge tassativa, tipo di formulazione precisa analitica: non si puó essere generali
    - non si fa ricorso all'analogia
- irretroattivitá
  + irretroattivitá della legge sfavorevole
  + retroattivitá della legge favorevole
*** Il Reato
illecito penale == reato
- non esiste reato non penale

Solo la persona umana é soggetto attivo del reato
Distinzione:
- capacitá penale
  + tutti
- capacitá alla pena
  + etá, capaciá di intendere e di volere

Il reato é integrato se tutti questi elementi sono compiuti
- condotta-evento
  + C: elemento essenziale, senza condotta non puó esserci reato
    - ma puó esserci reato senza evento, ~reato di pura condotta~
      + ~omissione~
        - ha essenza normativa, non fisica, in quanto consiste nel non compiere l'azione possibile che il soggetto ha il dovere giuridico di compiere
          + es. omessa denuncia da parte dal pubblico ufficiale
  + E: il risultato dell'azione o dell'omissione e deve essere legata a queste da nesso causale
    - c'é anche una differenza temporale tra evento e condotta, o anche spaziale
      + ~reati ad evento differito~
      + ~reati a distanza~
- rapporto di causalitá
  + conseguenza
  + in caso fortuito o forza maggiore: decade il rapporto di causalitá tra condotta ed evento
- offesa-elemento soggettivo
  + profilo psicologico, soggettivo
    - il fatto illecito deve appartenere psicologicamente all'autore della condotta
  + ~sistemo misto~
    - non basta la lesione oggettiva del bene o la sola volontá criminosa
    - sono necessari entrambi
  + responsabilitá colpevole
  + responsabilitá personalizzata

*** Colpevolezza
- imputabilitá
- conoscenza, conoscibilitá del precetto penale
  + non si puó sostenere di non conoscere una norma pubblica
- dolo o colpa
  + D: rappresentazione e volontá del fatto materiale
  + C: forma attenuata, eccezionale e minoritaria, sussidiaria, storicamente piú recente
    - é un rimprovero per aver realizzato, anche se involontariamente, un fatto-reato che avrebbe potuto essere evitato mediante l'osservanza esigibile di detta regola
      + mancanza della volontá del fatto tipico
      + inosservanza della regola di condotta
      + attribuibilitá dell'inosservanza all'agente
- preterintenzione
  + oltre il reato voluto
    - volontá di un evento minore e la non volontá di un evento piú grave

** Computer Crimes
Inseriti con Novelle nel codice penale
- fine anni '80 e inizio anni '90

- Legge 23 Dic 1993 n. 547
  - sazionato l'*accesso abusivo* ad un computer, software, sistemi telematici
  - se *danneggiamento* del sistema o dei dati: aggravante
  - natura di *documento informatico* ai supporti di qualunque specie contenenti dati
    + vengono inclusi anche supporti digitali
  - vengono permesse le intercettazioni informatiche o telematiche - 266-bis

- Convenzione di Budapest (Cybercrime) - Nov 2001
  a. delimitare definizioni comuni di reato
  b. definire poteri comuni di indagine
  c. predisporre mezzi di cooperazione internazionale
     - anche in via esecutiva
  d. definizioni
     a. *sistema informatico*
        + apparrecchiatura o gruppo di apparecchiature interconnesse che in base ad un programma compiono l'elaborazione automatica di dati
     b. *dati informatici*
        + presentazioni di fatti, informazioni o concetti in forma suscettibile di essere utilizzata in un sistema computerizzato
     c. *trasmissione di dati*
        + informazione computerizzata relativa ad una comunicazione attraverso sistema informatico, parte nella catena di comunicazione, indicando origine, destinazione, percorso, tempo, data, grandezza, durata, tipo del servizio

Il CC é un reato che
- implica l'uso di un sistema informatico (accesso abusivo al sistema)
- coinvolge un apparato informatico (diffamazione)

- Art. 615-tre c.p.
  - 1 a 3 anni per chiunque abusivamente si introduce in un sistema ... protetto ...
    + punibile a querela della persona offesa (negli altri casi si procede d'ufficio)
  - aggravanti:
    1. commesso da pubblico ufficiale o da un incaricato di un pubblico servizio / abuso della qualitá di operatore del sistema
    2. uso violenza sulle cose o alle persone
    3. ne deriva distruzione o danneggiamento del sistema / dati / informazioni / programmi
  - qualora i fatti riguardino sistemi ... di interesse militare / ordine pubblico / sanitá / interesse pubblico la pena si alza da 3 a 8 anni

- Cassazione Penale - 2012 (NB principio di tassativitá)
  + carte di debito o credito sono s.i.
  + casella di posta elettronica, spazio di memoria di un s.i., é un accesso a s.i.
  + una porzione di memoria protetta (es. da password) rivela la chiara volontá dell'utente di farne una spazio a sé riservato
*** Accesso Abusivo
+ *domicilio informatico*
  - deve essere protetto, anche da misure minime
  - *misura di sicurezza*
+ non hanno rilievo gli scopi e le finalitá che hanno soggettivamente motivato l'ingresso al sistema
+ *Locus Commissi Delicti*
  - l'introduzione abusiva ... integrati nel luogo in cui l'operatore materialmente digita la password di accesso o esegue la procedura di login, che determina il superamento delle misure di sicurezza
  - client / terminale
  - condotta criminosa fisicamente, nel senso di movimento muscolare dell'agente, é l'attivazione del terminale periferica da parte dell'operatore
+ in caso di *pubblico ufficiale*:
  - anche se non violando prescrizioni impartite per delimitarne l'accesso dall'amministratore del s.i.
  - é sufficiente che si acceda o si mantenga nel sistema per *ragioni ontologicamente entranee* a quelle per cui la facoltá di accesso gli é stata attribuita
+ reato sussiste anche se i dati cancellati abusivamente possono essere recuperati
  - nuova specifica previsione della *cancellazione* in accezione informatica e non semantica del termine, anche in presenza di backup o se eventualmente reversibili
  - coerente anche con l'interpretazione tradizionale del reato di danneggiamento, dove la condatta criminosa apporti una modificazione - anche impedendone anche parzialmente l'uso - che richieda un intervento ripristinatorio dell'essenza e della funzionalitá della cosa stessa
+ i *file* sono qualificabili come cose mobili e sono suscettibili di appropriazione rilevante
  - dimensione fisica che é determinata dal numero delle componenti, cifre binarie

** Documento e Identitá Digitale
- =Regolamente UE n.910/2014=
  + base normativa a livello comunitario per servizi di:
    - ident. digitale
    - firma elettronica
    - recapito elettronico
=eIDAS= electronic IDentification Authentication and Signature
Identificazione elettronica

- *identificazione elettronica*
  + processa per cui si fa usa di dati di identificazione personale in forma elettronica che rappresentano un'unica persona fisica o giuridica
  + =SPID= e Carta di identitá elettronica
    - per accedere ai servizi online della pubblica amministrazione e dei privati aderenti, con una coppia di credenziali personali
    - erogati da gestori di identitá, prestatori di servizi fiduciari
      + identity provider
    - 3 livelli di sicurezza (ISO/IEC DIS 29115)
      + userid/pass LoA2
      + OTP LoA3 - one time password
      + Dispositivo hardware LoA4
  + =AgID= - Agenzia per l'Italia Digitale
    - organismo di vigilanza
    - responsabile nello stato membro designante
- *Documenti*
  + elettronico
    - contenuto conservato in forma elettronica
  + informatico (particolare di d. elettronico)
    - rappresentazione informatica di atti, fatti o dati giuridicamente rilevanti
    - ha effetti sulla sfera giuridica del soggetto
    - valenza probatoria: Art.20 CAD
      + quando vi é apposta
        - firma digitale
        - firma elettronica qualificata
        - firma elettronica avanzata
        - o é formato, previa identif. informatica del suo autore (requisiti fissati da AgID Art.71), con modalitá tali da garantire la sicurezza, integritá e immodificabilitá e in maniera manifesta e inequivoca, con la sua riconducibilitá all'autore
        - in tutti gli altri casi il requisito della forma scritta e il suo valore probatorio sono liberamenti valutabili in giudizio (caso delle firme el. semplici)
  + analogico
    - rappresentazione non informatica di atti, fatti o dati giuridicamente rilevanti
- *Firme*
  + elettronica (semplice)
    - dati in forma elettronica, acclusi o connessi (tramite associazione) ad altri dati elettronici e utilizzati dal firmatario per firmare
      + dati utilizzati:
        - conoscenze dell'utente (password)
        - caratteristiche fisiche dell'utente (impronta digitale)
        - possesso di un oggetto da parte dell'utente (tessera)
  + elettronica avanzata (tecniche biometriche: firma grafometrica)
    - requisiti:
      + connessa unicamente al firmatario
      + idonea a identificarlo
      + creata con dati che il f. puó, con alto livello di sicurezza, utilizzare sotto il proprio esclusivo controllo
      + deve consentire l'identificazione di ogni successiva modifica di tali dati
  + elettronica (avanzata) qualificata
    - basata su un certificato qualificato per firme elettroniche
      + rilasciati da prestatori di servizi fiduciari accreditati, sotto la vigilanza dell'AgID
  + digitale - ~crittografia a chiavi asimmetriche~
    - normata dal CAD (Codice dell'Amministrazione Digitale, italiano)
      + particolare di firma e. qualificata
    - sistema di chiavi crittografiche, pubblica e privata, correlate tra loro
      + permettono di verificare la provenienza e l'integritá di un documento informatico o un insieme di documenti informatici
      + algoritmo di hash: collision resistant, non invertibile
        - genera digest usando la chiave privata memorizzata sul certificato di firma
        - il documento sottoscritto, l'impronta cifrata, il certificato dell'ente certificatore sono inseriti in una busta .p7m
        - viene controllato che l'impronta del file originale ricalcolata dalla stessa funzione sia uguale a quella recuperato decriptando il digest usando la chiave pubblica

** Posta Elettronica Certificata
=PEC=
Normato nel DPR 11 Feb. 2005,n.68
~sistema di posta elettronica~ nel quale é fornita al mittente documentazione elettronica, con valenza legale, attestante l'invio e la consegna di documenti informatici.
~obbligatorio~ per imprese e professionisti e di comunicarlo rispettivamente al registro imprese e agli ardini o collegi di appartenenza
Il proprio indirizzo di PEC é considerato domicilio digitale
- sono state introdotte sanzioni e obblighi nel Art.37 D.L.76/2020 per professionisti e relativi Collegi e Ordini di apportenenza e per le imprese in caso di mancata comunicazione del preprio domicilio digitale
  + diffida -> sospensione dall'albo (professionisti)
  + sanzione -> societá e imprese individuali

- Validitá giuridica
  + PEC -> PEC  -  piena
  + PEC -> PEO  -  intermedia

Il gestore del servizio, soggetto, pubblico o privato, che eroga il servizio di posta elettronica certificato e che gestisce domini di posta elettronica certificata

La ricevuta di avvenuta consegna fornisce al mittente prova che il suo messaggio di PEC é effettivamente pervenuto all'indirizzo elettronico dichiarato dal destinatario e certifica il momento della consegna
- *presunzione di conoscenza*
  + una volta che il sistema genera la ricevuta di accettazione e di consegna del messaggio nella casella del destinatario, se determina una presunzione di conoscenza da parte del destinatario, il quale é responsabile della gestione della propria utenza
    - il destinatario ha l'onere di dotarsi degli strumenti necessari per decodificare o leggere i messaggi inviatigli ma anche presidiare la propria casella procedendo alla periodica verifica delle comunicazioni regolarmente inviatigli
Le ricevute rilasciate dai gestori di PEC sono sottoscritte dai medesimi mediante una firma elettronica avanzata, generata automaticamente dal sistema di posta elettronica
- tipi di ric. avvenuta consegna
  + completa
    - postacert.eml
    - daticert.xml
  + breve
    - daticert.xml
    - breve estratto
  + sintetica
    - daticert.xml

- =Virus Informatico=
  + un programma informatico avente per scopo o per effetto il danneggiamente di un sistema informatico o telematico, dei dati o dei programmi in esso contenuti o ad esso pertinenti, ovvero l'interruzione, totale o parziale, o l'alterazione del suo funzionamento
  + il gestore del mittente é tenuto a non accettarli, informando tempestivamente il mittente
    - il gestore conserva i messaggi ricevuti per 30 mesi
  + il gestore del destinatario é tenuto a non inoltrarli al destinatario
    - tenuto a informare il gestore del mittente
    - conserva i messaggi ricevuti per 30 mesi

** Contratto
Un accordo di due o piú parti per costituire, regolare o estinguere tra loro un rapporto giuridico patrimoniale
- Digesto Romano
  + do ut des
  + do ut facias
  + facio ut des
  + facio ut facias
- Requisiti
  + accordo delle parti
    - tacito
      + intenzione manifestata dal comportamente delle parti
    - espresso
      + dichiarazione specifica
  + causa
    - se illecito il contratto é nullo
      + causa é illecita se contraria a norme imperative, all'ordine pubblico o al buon costume
    - obbligazioni naturali
      + obblicazione che trovano la propria fonte nei doveri morali e sociali che, pur non essendo giuridici, quindi non coercibili, non sono indifferenti per l'ordinamento
  + oggetto
    - caratteristiche:
      + possibile
      + lecito
      + determinato o determinabile
  + forma
    - espressa / tacita
    - scritta / orale
    - Contratti formali
    - Contratti a forma libera
    - Forma ad substantiam / Forma ad probationem

- Conclusione
  + scambio di proposta ed accettazione
    - concluso nel momento in cui chi ha fatto la proposta ha conoscenza dell'accettazione dell'altra parte
      + un'accettazione non conforme alla proposta equivale a nuova proposta, si invertono le parti
      + in email é sufficiente la conoscibilitá dell'accettazione
  + offerta al pubblico (sito internet)
    - proposta (con estremi essenziali)
    - invito a proposta (senza estremi essenziali)
    - acquirente invia accettazione con ~point and click~ sull'OK
  + comportamente concludente
    - se richiesto dal proponente o da natura affare a usi, il contratto é concluso con l'inizio di esecuzione

*** Telematico
Contratti stipulati per via elettronica, mediante l'uso di un computer
=Classificazioni=
- Diretto
  + conclusi e eseguiti online
  + software, dati
- Indiretto
  + conclusi online e eseguiti offline
  + beni materiali
- Sito
  + con pubblico indeterminato
- E-mail
  + tra parti determinate
- B to B
  + tra imprenditori (professionisti)
    - desciplina generale sui contratti
      + norme derogabili
      + clausole vessatorie (Codice Civile)
- B to Consumer
  + tra imprenditore e consumatore
  + consumatore parte piú debole, la legislazione va a suo favore
    - Legislazione speciale a tutela dei consumatori
      + norme inderogabili
        - diritto di recesso (14 giorni)
          + regola generale(CC) secondo cui un contratto non puó essere sciolto per mutuo consenso o per cause ammesse dalla legge
            - una delle cause é il caso del ~recesso unilaterale~, una parte puó esercitare la facoltá a determinate condizioni:
              + se é prevista nel contratto
              + finché il contratto non abbia avuto un principio di esecuzione
          + senza dover fornire alcuna motivazione e senza dover sostenere costi (tranne quelli specificati e previsti)
            - beni confezionati su misura o personalizzati
            - beni deteriorabili rapidamente
            - beni sigillati per motivi igienici in caso di apertura
          + non é dovuto se il bene é stato acquistato in fisico
            - ma esiste tutela per la garanzia per un bene difettoso
              + denunciare entro 8 giorni dalla scoperta
              + azione prescritta entro 1 anno dalla consegna
      + clausole vessatorie (Codice del Consumo)
        - considerate sempre nulle
=Soggetti=
- Professionista
  + agisce nell'ambito della propria attivitá imprenditoriale o professionale
- Consumatore
  + agisce per scopi estranei all'attivitá imprenditoriale o professionale

*** E-Commerce
=Direttiva 2000/31/CE= del 8.6.2000
é ogni tipo di attivitá commerciale online
- diritto di stabilimento e dell'esercizio
  + country of origin, luogo di esercizio dell'attivitá, non dove é collocato il server
  + criterio sostanzialistico, non piú formalistico
- responsabilitá degli operatori
  + non hanno necessitá di ulteriore autorizzazione per l'attivitá online
- comunicazioni commerciali e pubblicitarie
  + obbligo di informazione
    - dati per reperibilitá
    - prezzi
- contratti telematici
  + obblighi di informazione precontrattuali
    - fasi tecniche di conclusione del contratto
    - archiviazione o meno di tutte o parte delle informazioni
    - mezzi tecnici per correzione di errori
    - lingue disponibili
    - clausole e condizioni generali memorizzabili e riproducibili
