#+TITLE:  Economia e Diritto
#+ROAM-ALIAS: EGID
#+Teacher: Camillo Sacchetto, Fabio Montalcino
[[file:#university.org][#university]]

* Economia
(25/30 di scritto + esercitazioni)
** Business Model Canvas
Modello economico sostenibile
- backend - frontend
  + condividono la Value Proposition
    - risoluzione di un problema
    - ti do l'opportunita' di fare qualcosa che prima non facevi
- Customer Segments
- Channels

*** Customer Segments
gruppi di persone o organizzazione che la azienda mira a raggiungere, fornire
- bisogni comuni
- comportamenti comuni
- altri attributi

Le aziende devono fare scelte coscienziose per quanto riguarda che aree servire e che aree ignorare
- deve esserci una forte comprensione dei bisogni dei clienti
Divisioni
- bisogni
- canali di distribuzione
- tipi di relazione
- profittabilita'
- aspetti dell'offerta
Q:
- per chi creo valore
- chi sono i nostri clienti piu' importanti

Segmenti
- mass market
  + il business model non distingue tra customer segments
  + i canali e le relazioni si concetrano su un largo gruppo di clienti
- niche market
  + Specifico e specializzato
  + spesso tratta relazioni tra fornitore-compratore
- segmentato
  + prodotto simile ma offerto a diversi gruppi
- diversificato
  + segmenti diversi e prodotti diversi
- multi-piattoforma
  + permettono l'incontro tra offerta e domanda
  + non forniscono nulla di reale se non la piattaforma
*** Value Proposition
Tutta la struttura dovra' essere compatibile con questa sezione
- Qual'e' lo scopo del prodotto e i suoi usi
- A chi e' mirato questo prodotto, dove si collocano
  + decisori o utenti, clienti (e' disponto a riconoscere un valore non necessariamente monetario)
  + che prodotto indiriziamo ad ogni segmento di clientela
    - Valori diversi
      + quantitativo
        - prezzo
        - velocita' di consegna
      + qualitativo
        - design
        - esperienza cliente
- Che bisogni soddisfa il prodotto
  + che problema risolve
- Come trasferisco il prodotto al cliente
- Qual'e' il posizionamento del prodotto, definizione del prezzo

Elementi
- novita'
- performance
- custom
- ti consento di fare meglio il tuo lavoro
- Design
- Brand/Status
- prezzo
  + scelta in base all'aspettativa delle clientela
- aumento del margine di guadagno per i clienti
- riduzione del rischio
- accessibilita'
  + a servizi non normalmente accedibili
- convenienza/usabilita'

*** Channels
Strumenti fisici o virtuali che permettono di raggiungere i segmenti di mercato
I canali sono insiemi di strumenti con cui l'azienda consegna la Value Proposition ai clienti
- *Funzioni*
  + Rendere a conoscenza dell'offerta dell'azienda il cliente
  + Consentire una valutazione della value proposition corretta da parte del cliente
  + Permettere l'acquisto del prodotto
  + Trasferire materialmente o meno il prodotto
  + Assicurare supporto al cliente (assistenza)

Da considerare l'efficienza dei canali e della loro integrazione reciproca
anche rispetto a canali diretti e indiretti, piú il cliente finale é lontano piú sará difficile analizzarlo.

*** Customer Relationships
Spesso sono bidirezionali
- 3 *obiettivi*
  + Acquisizione di nuovi target, aumento della base di clientela
  + Mantenimento della base di clientela
  + Aumento della vendita, upselling e cross-selling

Le diverse modalitá devono essere integrate, non devono creare confusione nel cliente: in questo caso é alto il rischio di perdita del cliente.

- *Modalitá*
  + Assistenza personale
  + Assistenza personale dedicata, molto piú costruito sulle singole esigenze
  + Self-service
  + Servizi automatizzati
  + Comunitá
    - acquisti di gruppo
  + Co-creazione
    - Kickstarter, Youtube, Amazon


*** Revenue Streams
L'utile o margine netto che si ricava
- transazioni unica una tantum di un cliente
- transazioni ricorrenti

Domanda importante: a cosa il cliente é disposto a riconoscere un valore
- ci sono diversi modi per generare _revenue stream_
- ció che conta é la somma complessiva dei R.S.

Modalitá
- venditá di asset
- pagamento in base all'uso
- pagamento ad iscrizione
- affitto/leasing/prestito
- pagamento di licenza
  + uso di prodotti ~intangible~
- brokeraggio
- pubblicitá
Meccanismi di definizioni del Prezzo
- fisso
- dinamico
  + in base al momento, al metodo di acquisto, il prezza cambia
  + negoziazione
  + al momento in base a domanda e offerta

*** Resources
Gli asset che permettono di non venir meno alla Value Proposition
Le risorse si dividono in:
- fisiche - tangibili
- finanziarie
  - vantaggio nel trasferimento della risorsa
- intellettuale
- umane
Ulteriormente divise in:
- proprietarie o gestite dall'azienda
- acquisiti da partner
Quest'ultima distinzione non importa molto dal punto di vista della Value Proposition

* Diritto
Esistono diverse fonti di Diritto
- nazionali
  + sentenze
  + DPCM
  + DPC
- internazionali

Esistono conflitti di fonti
- nazionali | comunitarie
- gerarchia delle fonti

Definizione dei soggetti
- giuridica
  + aggiunge sfumature
- tecnica

Quando si regolamenta - tecnica linguistica:
1. tecnica analitica
   - disciplinare soggetti utilizzando un elenco analitico ricade nella regolamentazione
     + cio' che non e' citato rimane non disciplinato, allora va estesa eventualmente per analogia
   - vietata nel diritto penale italiano
2. tecnica per principi
   - si mantiene una generalita'
   - va sempre fatto un passaggio logico quando questa e'
applicata
   - e' facilmente ambigua

3. Settori
   - civile
   - penale
   - amministrativo
   - del lavoro

** Responsabilita' ISP
Tematica sorta nei primi anni 2000
Scelta della *fonte*
- Direttiva Comunitaria 2000/31 (!Regolamento Comunitario)
  + commissione europea
    - da' dei parametri a tutti i paesi membri
    - che dovranno essere applicati dai singoli paesi
      + se non in linea potranno essere disapplicati
  + considerando che... n.42
    - il processo tecnico di attivare e fornire accesso ad una rete
    - l'attivita' e' meramente tecnica automatica e passivo
    - non conosce ne' controlla le informazioni
- Decreto Legislativo n.70 2003
*** Art. 17
1. assenza dell'obbligo generale di sorveglianza da parte del prestatore e di ricerca attiva
2. tenuto ad
  a. informare l'autorita' qualora sia a conoscenza di attivita' o informazioni illecite riguardanti un suo destinatario
  b. fornire a richiesta delle autorita' competenti le informazioni in suo possesso
3. prestatore civilmente responsabile del contenuto di tali servizi in caso non ha agito prontamente per impedire l'accesso a detto contenuto
  a. elemento integrativo da parte dell'Italia

*** Art. 14
Responsabilita' di Mere Conduit (semplice trasporto, Telecom)
1. colui che trasmette su una rete informazioni fornite da un destinatario o fronisce accesso alla rete, non e' responsabile delle informazioni trasmesse a condizione che
   a. non dia origine alla trasmissione
   b. non selezioni il destinatario della trasmissione
   c. non selezioni ne' modifichi le informazioni trasmesse
2. la memorizzazione automatica, intermedia e transitoria delle informazioni trasmesse deve servire solo alla trasmissione e la sua durata non deve eccedere il tempo ragionevolmente necessario a tale scopo
3. L'autorita' puo' esigere, anche in via d'urgenza, che il prestatore impedisca o ponga fine alle violazioni commesse

*** Art. 15
Responsabilita' nell'attivita' di memorizzazione temporanea (caching, Google)
1. il prestatore non e' responsabile della memorizzazione temporanea delle informazioni effettuata al solo scopo di rendere piu' efficace il successivo inoltro ad altri destinatari a loro richiesta
   a condizione che
   a. non modifiche tali info
   e. agisca prontamente per rimuovere le informazioni e senza indugio
2. L'autorita' puo' esigere, anche in via d'urgenza, che il prestatore impedisca o ponga fine alle violazione commesse
*** Art. 16
Responsabilita' nell'attivita' di memorizzazione di informazioni (hosting)
1. Memorizzazione di info fornite da un destinatario
   1) non sia a conoscenza del fatto che l'attivita' o l'informazione e' illecita
   2) *non appena* sia a conoscenza di tali fatti, *su comunicazione delle autorita'*, agisca immediatamente per rimuovere le informazioni o per disabilitarne l'accesso
      - aggiunta italiana, ha generato una ambiguita'
2. 1 non si applicano se il destinatario del servizio agisce sotto l'autorita' o il controllo del prestatore
3. L'autorita' puo' esigere, anche in via d'urgenza, che il prestatore impedisca o ponga fine alle violazione commesse

*** Art. 17 2019

*** Sentenze
**** Case history RTI
Gruppo Mediaset
- Febbraio 2010 - RTI | Youtube
  - diritto d'autore delle reti Mediaset
  - pone a carico del host provider l'obbligo di rimuovere immediatamente non appena avuto conoscenza di tale illiceita'
    + anche su comunicazione dal titolare dei diritti
  - Youtube non ha agito immediatamente
- Settembre 2011 - RTI | Yahoo!
  - l'inattivita' del prestatore di servizio, nonostante le segnalazioni delle presenza di numerosi contenuti in violazione dei diritti d'autore, lo renda colposamente responsabile
- Ottobre 2011 - RTI | Choopa , VVB
  + la non responsabilita' dell'hosting provider si ha purche' il prestatore del servizio non sia effettivamente a conoscenza dell'illiceita' o di fatti e circostanze che rendono manifesta detta illiceita'
  + ricorso respinto perche' RTI aveva inviato un'unica diffida senza una dettagilata e specifica indicazione dei video da rimuovere
  + non conta il paese in cui e' basato il provider, conta il luogo dove viene commesso l'illecito
    - RTI aveva visto lesi i suoi diritti nell'area del mercato italiana, quindi
**** Case history Google
Gia' la commissione europea specificava gli stati potessero specificare leggi in tema di motore ricerche
- Maggio 2012 - Meneghetti | Google (utente anonimo)
  - in mancanza di un *ruolo "attivo" sulla conoscenza e controllo dei dati memorizzati* il motore di ricerca non e' responsabile dei contenuti immessi da terzi in rete, anche laddove gli stessi siano raggiungibili in quanto risultanti delle ricerche effettuate sullo stesso motore.
    + il mettere a disposizione non e' un ruolo attivo, in quanto inconoscibile
  - e' necessario che un organo giurisdizionale competente ne dichiari la effettiva illiceita' dei dati
- Febbraio 2013 - caso Vividown
  + video di violenze e insulti sulla piattaforma Google Video
  + Milano perche' sede Vividown
  + Google non responsabile del reato di diffamazione, in quanto rimosso appena segnalato
  + (primo grado) ma c'e' un trattamento illecito dei dati del ragazza disabile (dati sensibili) che non ha informato gli utenti della loro possibile responsabilita'
    - (secondo grado) ribaltata la responsabilita'
      + (cassazione) il decreto legislativo non si applica nel campo del diritto e alla riservatezza, Google ha fatto anche indicizzazione (azione attiva?) oltre che il mero upload
        - non c'e' trattamento illecito perche' *mancava della conoscenza dell'illecito,* anche avendo rimosso il contenuto collaborando con le autorita'
- Marzo 2009 - AVIS | SIXT, Google ADWords
  + concorrenza sleale, in quanto digitando AVIS si era reindirizzati
  + Comportamento abusivo del soggette che utilizzi come keyword segno distintivo altrui
    - la tecnica di marketing telematico ADWords, di per se, e' lecita
    - richieste di condanna respinte per carenza di legittimazione processuale (sarebbe dovuto essere Google Ireland)
- Marzo 2011 - | Google Autocomplete
  + ruolo attivo, evidente valenza diffamatoria
  + intervento sul software in modo da rimuovere l'associazione diffamatoria
- Maggio 2012 - | Google Autocomplete
  + Effetto del funzionamento del servizio completamente automatico, del tutto privo di valenza diffamatoria
  + non c'e' l'elemento del dolo, inoltre una azienda non ha una chiara componente psicologica
- Marzo 2013 - | Google Autocomplete
  + Secondo l'attore, Google e' un content provider, in quanto le funzioni di completamento automatico e di generazione di ricerche sono messe a punto dal provider
  + il Tribunale esclude la qualificazione di content provider
    - in quanto un sistema di attivazione del servizio e non certo di una funzione, ne' un contenuto
    - riproduce statisticamente il risultato delle ricerche piu' popolari
    - i risultati non costituiscono un archivio, ne' sono strutturati, organizzati o influenzati da Google
    - trattando di un Algoritmo non e' applicabile un Diritto prettamente umano
- Maggio 2013 - Reclamo al Collegio | Google Autocomplete
  + l'automatismo non e' sinonimo di neutralita' dell'ISP
  + nel suo ruolo svolge ulteriori attivita' non meramente automatiche e necessarie per la sola trasmissione o raccolta dei contenuti
  + inoltre l'elemento di lucro pone un ulteriore aspetto attivo da parte dell'azienda

**** Mediaset vs Facebook
=Roma, 20 Feb 2019=
Pagina facebook dedicata ad un cantone animato, con link a contenuti protetti da diritto d'autore.
Facebook non rimosse i contenuti, si passó al tribunale.
Caso storico per la presa di posizione nei confronti del Social Network
- definito come ISP
  + sia caching che hosting
- riconosce la responsabilitá del SN per violazioni avvenuti tramite ~linking~
  + quindi con pubblicazioni esterne alla piattaforma vera e propria
Focebook afferma la non correttezza del giudice, volendo il giudizio in California
- convenzione di Bruxelles '68 (principalmente tra paesi Europei, non USA)
  + cerca di chiarire dove va fatta la contestazione
- viene deciso che il mercato della parte lesa, luogo dell'evento in questione
  + Italia
Il link é una comunicazione al pubblico, l'articolo 13 della /riforma del diritto d'autore nel mercato unico digitale/ cita:
"I fornitori di servizi che fanno _comunicazione al pubblico_ devono ottenere l'autorizzazione per la messa a disposizione di contenuti dai titolari di diritti"
- qui c'é illecito nella non autorizzazione da parte di Mediaset, proprietaria dei diritti

**** Direttiva UE 2019/790 Del Parlamento Europeo e del Consiglio
=Direttiva Copyright=
In rif. al prestatore di un servizio dell'informazione... *va esclusa la responsabilitá prevista dall'art. 14 della direttiva 31/2000* ... dopo aver preso conoscenza, mediante informazione fornito dalla persona lesa o in altro modo, della natura illecita di quei dati o attivitá.
- se l'illiceitá é manifesto é obbligo del provider sospendere e rimuovere, se non manifesta va chiarita riferendosi, puó essere anche un elemento esterno a renderla manifesta
**** RTI vs Yahoo
=Corte di Cassazione, 19 Mar 2019=
Presunta violazione di diritti d'autore da parte di Yahoo
- DIFESA: la non immediata attivazione non implicava un illecito un quanto sito di Hosting Passivo
La giurisprudenza della Corte di giustizia ha accolto la nozione di hosting provider attivo riferendosi a prestatori che non conoscono né controllano le informazioni trasmesse o memorizzate dalle persone alle quali forniscono i loro servizi
- Cassazione: provider qualificabile come hosting attivo quando *completa e arricchisce* in modo non passivo *la fruizione dei contenuti*

Alla luce... l'hosting passivo é responsabile per non avere prevveduto all'immediata rimozione dei cantenuti illeciti o per aver continuato a pubblicarli

**** L'Oréal vs Ebay
- la disposizione della direttiva ~2000/31/CE art. 14~ deve essere interpretata non soltanto in considerazione del suo tenore letterale, ma anche del suo contesto e degli scopi perseguiti dalla normativa di cui essa fa parte

Sostanza sopra la forma

- Per quanto concerne l'art. 14 é necessario verificare se il prestatori di servizi svolge un ruolo attivo, anche ottimizzando la prestazione delle opere o altro materiale caricati o promuovenali, indipendentemente dalla naturo del mezzo utilizzato a tal fine.
  Dovrebbero adottare misure appropriate e proporzionate per garantire la protezione di tali opere a altro materiale, ad esempio tramite l'uso di tecnologie efficaci.
  - questo anche quando i prestatori di servizi rientrano nell'esenzione di responsabilitá di cui all' ~art. 14 della direttiva 2000/31/CE~


**** TikTok vs Garante Privacy
Gen 2021, strangolamento bambina di 10 anni a seguito della Blackout Challenge
- Fonti
  - Regolamento UE 2016/679
    - in vigore dal 2018
  - Decreto Legislativo 101/2018

Giá a dicembre il Garante della Privacy aveva sollevato delle contestazioni a TikTok
- Divieto di iscrizione ai piú piccoli facilmente aggirabile
- Scarsa tutela dei minori
- Poca trasparenza nelle informazioni resa agli utenti
- Impostazioni predefinite non rispettose della privacy
  - profilo pubblico di default

 Il limite d'etá prima del regolamento prevedeva 13 anni, questo per la legge federale USA:
 COPPA, prescrive che nessuno persona giuridica puó raccogliere dati relativi a minori di 13 anni
 In Italia il limite é definito a 14 anni.

 *Art. 66* procedura d'urgenza
 - per proteggere i diritti e le libertá degli interessati, un'autoritá, puó adottare immediatamente misure provvisorie intese a predurre effetti giuridici nel proprio territorio
   - periodo di validitá determinato che non supera i tre mesi

 Provvedimento dispone la misura della ~limitazione provvisoria~ del trattamento, vietando l'ulteriore trattamente doi dati degli utenti che si trovano sul territorio italiano per i quali non vi sia assoluta certezza dell'etá
 - prima ancora di sentire la controparte, ma ha giá valore di legge

TikTok si é impegnato ad adeguarsi alle richieste del Garante privacy
- blocco degli utenti per la richiesta di inserimento dell'etá
- miglioramento della propria informativa privacy in un linguaggio anch piú accessibile
- introduzione di report di utenti minori dei 14 anni
- banner di informazione sull'impostazione del profilo da pubblico a privato
Il garante ha avviato una collaborazione con il telefono Azzurro
- campagna di sensibilizzazione con l'obiettivo di richiamare i genitori a svolgere un ruolo attivo di vigilanza

** Computer Crimes
*** Principio di legalitá
3 presupposti
- riserva di legge
  + solo il potere legislativo, espressione del paese, ha manopolio normativo in materia penale
- tassativitá
  + tecnica di legge tassativa, tipo di formulazione precisa analitica: non si puó essere generali
    - non si fa ricorso all'analogia
- irretroattivitá
  + irretroattivitá della legge sfavorevole
  + retroattivitá della legge favorevole
*** Il Reato
illecito penale == reato
- non esiste reato non penale

Solo la persona umana é soggetto attivo del reato
Distinzione:
- capacitá penale
  + tutti
- capacitá alla pena
  + etá, capaciá di intendere e di volere

Il reato é integrato se tutti questi elementi sono compiuti
- condotta-evento
  + C: elemento essenziale, senza condotta non puó esserci reato
    - ma puó esserci reato senza evento, ~reato di pura condotta~
      + ~omissione~
        - ha essenza normativa, non fisica, in quanto consiste nel non compiere l'azione possibile che il soggetto ha il dovere giuridico di compiere
          + es. omessa denuncia da parte dal pubblico ufficiale
  + E: il risultato dell'azione o dell'omissione e deve essere legata a queste da nesso causale
    - c'é anche una differenza temporale tra evento e condotta, o anche spaziale
      + ~reati ad evento differito~
      + ~reati a distanza~
- rapporto di causalitá
  + conseguenza
  + in caso fortuito o forza maggiore: decade il rapporto di causalitá tra condotta ed evento
- offesa-elemento soggettivo
  + profilo psicologico, soggettivo
    - il fatto illecito deve appartenere psicologicamente all'autore della condotta
  + ~sistemo misto~
    - non basta la lesione oggettiva del bene o la sola volontá criminosa
    - sono necessari entrambi
  + responsabilitá colpevole
  + responsabilitá personalizzata


*** Colpevolezza
- imputabilitá
- conoscenza, conoscibilitá del precetto penale
  + non si puó sostenere di non conoscere una norma pubblica
- dolo o colpa
  + D: rappresentazione e volontá del fatto materiale
  + C: forma attenuata, eccezionale e minoritaria, sussidiaria, storicamente piú recente
    - é un rimprovero per aver realizzato, anche se involontariamente, un fatto-reato che avrebbe potuto essere evitato mediante l'osservanza esigibile di detta regola
      + mancanza della volontá del fatto tipico
      + inosservanza della regola di condotta
      + attribuibilitá dell'inosservanza all'agente
- preterintenzione
  + oltre il reato voluto
    - volontá di un evento minore e la non volontá di un evento piú grave
