:PROPERTIES:
:ID:       93041c48-ddc0-41d2-a876-ec728d1e122f
:END:
#+title: L'ansia del recupero
#+date: [2021-12-27 Mon 23:02]
#+filetags: video
- Source: https://www.youtube.com/watch?v=jIienq8Pego
- Channel: WesaChannel
- Related: [[id:0934f9bf-0c66-4fa1-9777-7d17d1da54c5][Antibiblioteca]], [[id:22e78f36-a7a6-41c3-9e22-0fbc9e4b457a][Consumer Culture]]

* Trascritto
#+begin_quote
Troppa roba.

Un’etichetta, uno scomparto, un vano: visione rimandata. Un libro fatto di segnalibri: la lista dei recuperi, la lista dei papabili. L’infinita lista delle cose che non so, che non vedo, che non afferro ma che, nel mentre, catalogo.

Opere, persone. Ciascuna che brilla nel sole di domani.

La testa dentro, la spugna grigia, piena di riferimenti, titoli di articoli, link, preview, hands on, leggi dopo, guarda più tardi, aggiungi all’elenco: superfici promettenti. _Nella testa fuori, la protesi digitale, la conoscenza messa via che rimarrà muta quando mancherà la mente che l’ha sognata._ Il tesoro di una vita a venire venuta meno.

L’infinito è inattingibile.

Capienti come bacheche siamo le prime pagine dei nostri archivi, siamo sommari, ambizioni sproporzionate al nostro parco durare, progetti di immortalità che non vivremo e che nessuno compirà. Le tre cose fatte nei tre giorni vissuti saranno un ben misero lascito rispetto alla smisuratezza cui avremo alluso, programmandola per la nostra anima immortale (che, benché irreperita, vivendo supponemmo).

Alla fine delle Invasioni Barbariche la telecamera scorre sui volumi della libreria: i libri letti come mappa per un’archeologia del lettore. Non è che la scorza.

Percorrendo i nostri archivi digitali potremo scoprire chi volevamo essere, quale percorso additavamo per noi stessi. L’infinita frazione di infinito che, fossimo durati, saremmo stati.

Esco. Le cose semplici. La Rete è così grande che non mi ero accorto di passare fra le sue maglie. Me ne vado in giro.
#+end_quote
