:PROPERTIES:
:ID:       c2bda57f-a02a-460c-96a2-796dd2fee708
:END:
#+title: Learn Quantum Computing with Python and Q#
#+date: [2022-03-29 Tue 18:05]
#+filetags: book
Sarah Kaiser, Christopher Granade, /Learn Quantum Computing with Python and Q#/, 2021, Manning

- Tags: [[id:6e504ff7-9a50-4a47-901d-4c524c229bc6][Quantum Computing]], [[id:96019e24-7f04-44ec-9bfe-727a0098d761][Q#]]
- Code: https://github.com/crazy4pi314/learn-qc-with-python-and-qsharp

* Concepts
** Qubits
Quantum analogue to the classical /bits/
*** Quantum Random Number Generation
=QRNG=

Randomness is important, expecially where security is concerned.
We need =RNG= that our adversary can't predict.
While =RSA= relies on /just/ the assumption that factoring large numbers is hard the randomness of quantum mechanics is guaranteed by physics.
Generating truly random numbers allows the implementation of a secure [[id:51177984-16bc-4c8b-8b69-969dba9f1dd9][One-time Pad]].

The algorithm:
1. allocate a =qubit=
2. apply the =Hadamard= instruction to the =qubit=
3. measure the =qubit=

** Quantum Key Distribution
** Nonlocal Games
** Teleportation & Entanglement
* Programming
** Setting Up the Environment
- https://docs.microsoft.com/en-us/azure/quantum/install-overview-qdk

The authors use Anaconda w/ [[id:b7330c27-133a-4c8a-9e5b-17f8c1d71f0b][Python]] 3 and the Conda package manager for the qsharp packages.

On Arch the =anaconda= package on the =AUR= installs everything but you need to add it to =PATH=:

#+begin_src bash
PATH=/opt/anaconda/bin:$PATH
#+end_src

Then you set the environment via =environment.yml= in the book's repo.

#+begin_src bash
$ conda env create environment.yml
$ conda activate qsharp-book
#+end_src

- for this =conda= needs to be set up on the console (=bash=, =zsh=, ...)

After this the last thing to setup is =dotnet=, download the appropriate =Core SDK=.
Install project templates:

#+begin_src bash
$ dotnet new -i "Microsoft.Quantum.ProjectTemplates"
#+end_src


and to use them:
#+begin_src bash
$ dotnet new console -lang Q# -O MyProject
#+end_src


Then to have language hinting on =VS Code= you need to install the extension =Microsoft Quantum Development Kit=
- not available on the FOSS version of =VS Code= on the =AUR=

For Jupyter Notebooks you can install =IQ#=
#+begin_src bash
$ dotnet tool install -g Microsoft.Quantum.IQSharp
$ dotnet iqsharp install
#+end_src

If there are problems with ~iqsharp~ install the correct runtime, =aspnet-runtime= on the =AUR=.
** Q#
** [[id:d7686f15-7f24-476e-9ecf-87ef577d5a4c][Deutsch-Jozsa Algorithm]]
To use the algorithm on function $f$ to decide whether it is balanced or constant we need to define an /oracle/ for that function.
- this is because functions can be /unreversible/
  + ~id~, reversible
  + ~not~, reversible
  + ~zero~, unreversible
  + ~one~, unreversible
  + constant functions are unreversible as they lose track of which input resulted in the output

#+begin_quote
Oracles are unitary matrixes defined by applying $f$ conditionally to the labels for qubits states, applying an oracle twice results in the identity \(I\)
#+end_quote

To make a =classical reversible function= $h$ from the unreversible $f$:
\[h(x,y) = (x,y \oplus f(x))\]

In the same way we can make a =reversible quantum operation= or =oracle=:
\[U_{f} |x \rangle | y \rangle = | x \rangle | y \oplus f(x) \rangle\]
- $x$ is the =control qubit=
- $y$ is the =target qubit=

The algorithm works by using a quantum programming technique colled /phase kickback/.
- the fact that the input qubit's state changes base on transformations defined in the output qubit

  The algorithm can be extended to $n$ qubits with functions of form
  \begin{centre}f(x_{0}, x_{1},\cdots,x_{n})\end{centre}
  and n-qubits oracles:
  \begin{centre}U_{f}|x_{0} x_{1}\cdots x_{n}y\rangle = | x_{0} x_{1}\cdots x_{n}\rangle \otimes | f(x_{0}, x_{1},\cdots,x_{n}) \oplus y\rangle\end{centre}

** Quantum Sensing
* Applied Quantum Computing
** Chemistry
** Searching
*** Grover's Search Algorithm
** Arithmetic
*** Shor's Algorithm
