:PROPERTIES:
:ID:       88805531-eaa4-44f1-b819-8b25a84d96ba
:END:
#+title: Linked Data: Evolving the Web into a Global Data Space
#+date: [2022-11-30 Wed 16:24]
#+filetags: book
T. Heath, C. Bizer, /Linked Data: Evolving the Web into a Global Data Space/, 2011, Morgan & Claypool

* Summary
#+begin_quote
This book provides a conceptual and technical introduction to the field of Linked Data. It
is intended for anyone who cares about data – using it, managing it, sharing it, interacting with it
– and is passionate about the Web. We think this will include data geeks, managers and owners
of data sets, system implementors and Web developers. We hope that students and teachers of
information management and computer science will find the book a suitable reference point for
courses that explore topics in Web development and data management. Established practitioners of Linked Data will find in this book a distillation of much of their knowledge and experience, and a reference work that can bring this to all those who follow in their footsteps.
#+end_quote
* Notes
