:PROPERTIES:
:ID:       5571d2a4-bee6-4008-aded-cbd94c8c782d
:END:
#+title: On Microkernel Construction
#+date: [2023-03-12 Sun 20:40]
#+filetags: paper
- Source: https://doi.org/10.1145/224056.224075
- Author: [[id:ab720e80-1db4-44d6-addf-282ca98459dc][Jochen Liedtke]]
- Related: [[id:ad8e431b-7af6-4eb9-99a7-41af9cd0c4ce][Microkernel Based Systems]]

* Claim
The shortcomings of the $\mu$​-kernel are to be attributed mostly to overloading the kernel and/or improper implementations.

* Summary
The author finds that the shortcoming in performance measured in microkernels dismiss the entire category without understanding the reason of the issue, whether it was caused by the approach of the $\mu$​-kernel, by the concepts implemented or by the implementation itself.
The paper defines the basic $\mu$​-kernel concepts, primitives that are to be implemented. These are concepts that if moved outside of the kernel would compromise the functionality of the system.
These concepts are:
- independence
- integrity
* Notes
$\mu$​-kernels are costructed on the basic idea that one must implement whatever possible outside of the kernel[fn:kernel The kernel is commonly used to denote the part of the =OS= that is mandatory and common to all software.].
Advantages:
- clear kernel interface enforces a more modular system structure
- servers can use the mechanisms provided by the =MK= like ony other program, server malfunction is isolated
- more flexible system, different =API=​s, different servers can coexist
