:PROPERTIES:
:ID:       fa31fd31-a6a5-40ea-b22f-7950a4e0322b
:END:
#+title: phon
#+date: [2023-01-27 Fri 17:09]

* Motivazioni
Il dominio scelto per lo svolgimento di questo progetto è stato quello della fotografia.
Questa arte è stata fin dalla sua nascita nel primo ottocento un grande motore culturale, sociale e politico e avrà sicuramente ancora per molto tempo un ruolo centrale nella cultura umana.

Questo senza ignorare la centralità rinnovata che il linguaggio per immagini continua a sviluppare nel mondo dei social network e  della messaggistica istantanea.

Ci sono diversi progetti di archiviazione e catalogo di fotografie in rete, le più importanti sono:
- [[https://www.flickr.com/commons][The Commons]]
  + progetto di *Flickr* lanciato nel 2008 in collaborazione con la /Library of Congress/, con l'obiettivo di aumentare l'accesso a collezioni fotografiche pubbliche
- [[https://www.europeana.eu/en/collections/topic/48-photography][Europeana]]
  + progetto europeo in collaborazione con migliaia di archivi, biblioteche e musei per condividere il bene culturale europeo
- [[http://apolloarchive.com/][Project Apollo Archive]]
  + progetto composto da scan fotografiche del Kennedy Space Center di archiviazione e catalogo delle fotografie scattate durante l'allunaggio
* Requisiti
- *Finalità*
  + creare una tassonomia il più semplice e chiara possibile per descrivere il dominio
  + facilitare la ricerca e la scoperta di opere tramite collegamenti tra risorse
- *Task*
  + consultazione delle specifiche tecniche delle fotografie
  + verifica di informazioni sulle fotografie
  + esplorazione del grafo tramite collegamenti inferiti ad altre fotografie (stesso autore, stesso genere, stessa macchina fotografica)
- *Target Utenti*
  + appassionati
  + professionisti
  + storici
* Descrizione del dominio
Partendo dalla definizione Treccani di fotografia:
#+begin_quote
Procedimento che, mediante processi chimico-fisici, permette di ottenere, servendosi di un apposito apparecchio (macchina fotografica), l’immagine di persone, oggetti, strutture, situazioni: una lastra o una pellicola trasparente rivestite di un’emulsione sensibile alla luce (o ad altra radiazione attinica, per es. i raggi X) sono impressionate dalla luce riflessa dal soggetto attraverso l’obiettivo della macchina, e sono sviluppate ed eventualmente riprodotte su altro supporto di materiale fotosensibile per stampa a contatto o per ingrandimento in quante copie si vogliono, di identico o differente formato; si distinguono, sotto l’aspetto tecnico e del risultato, una f. in bianco e nero e una f. a colori, secondo che si riproduca il soggetto rendendo con sfumature più o meno intense di grigio le differenze di colore e di luminosità, oppure che lo si riproduca, grazie a una tecnica più complessa, con i suoi colori naturali.
#+end_quote

Il dominio si articola quindi in:
- Fotografia
  + caratterizzabile dal periodo storico e dal luogo in cui è stata scattata
- Agenti
  + Soggetto
  + Autore
- Attrezzatura
  + Corpo Macchina
  + Lente
- Medium
  + Pellicola
  + Digitale
  + Stampa di qualche tipo
- Genere
  + Ritratto
  + Glamour
  + Natura
  + etc.
** Sitografia
1. https://en.wikipedia.org/wiki/Photography
2. https://en.wiktionary.org/wiki/photography
3. https://sigma.ontologyportal.org (Photographing, Photography, Photograph, Camera, Lens)
4. http://wordnetweb.princeton.edu/
5. https://www.treccani.it/vocabolario/fotografia/
* Documentazione
* OOPS
=OntOlogy Pitfall Scanner=
* Visualizzazione
