:PROPERTIES:
:ID:       66f28b61-8380-4480-9cb4-43cf319d6e9a
:END:
#+title: Quality of Service in Computer Networks
#+date: [2023-02-27 Mon 10:57]
#+FILETAGS: erasmus university compsci

* Components & Modules
- time-space multiplexer

* Homogeneous Markov Processes
For *irreducible aperiodic* =MC=
\[p_{j} = \sum_{i\in S} p_{i}P_{ij}  \quad \forall j\in S\]

Global balance
\[\sum_{i \in S / \{j\}}} p_{i}p_{j}\]

** Non-stationary case
Probability density $q$ are elegant solution to have simpler equations, independent of time-scale.
- assuming transition probabilities where we zoom on the time axis to where the transition is smooth
  + can be approximated to a linear function
  + $$p_{ij}(s)=q_{ij}\cdot s + o(s) \quad j\neq i$

*Conditional* and *absolute* transition probability:
\[p_{ik}^{\star}(s)=p_{i}(t)\cdot p_{ik}(s)\]

*Kolmogoroff Equation*

** Stationary case
\[p_{X}= \lim_{t\to \infty}p_{X}(t)\]
\[\lim_{t\to\infty\}]

Statistical equilibrium for the states:
\[q_{k}p_{k}=\sum_{i\neq k} q_{ik}\cdot p_{i}\]

*Generalised* state equations:
\begin{align*}
p_S = \sum_{k\in S} p_k \\
q_k = \sum_{i\neq k} q_{ki}
\end{align*}

You can generalize a set of state to abstract into a single bigger markov state that includes them.
* Communication Traffic as Random Process
In formulas $t$ and $\Delta t$ are interchangeable.
** State process
** Call process
\begin{align*}
q_{A}= \lambda\\
F_{A}(t)=P(T_{A} \leq t)\\
E(T_{A}) = \frac{1}{\lambda}\\
c = \lambda \\
F_{A}(t) = P(T_{A} \le t) = 1 - e^{-\lambda t} \\
F_{A}^{C}(t) = P(T_{A} > t) = e^{-\lambda t} \\
\end{align*}
** End process
\begin{align*}
F_H(t) &= P(T_H \leq t) = - e^{\frac{t}{h}}\\
\text{end rate: } \epsilon &= \frac{1}{h}\\
p_{E1}&=1-e^{-\frac{\Delta t}{h}}+o(\Delta t)\\
\text{probability density: } q_{E,x}&=\lim_{\Delta t \to 0}\frac{P_{E,x}(\Delta t)}{\Delta t} \text{ so } q_{E,x}=\frac{x}{h}
\end{align*}
* One-dimensional birth-death processes
\beg
\sum P_i = 1 \\

\end
To not have $n$ members to the equations we use a generalised state $S_x$ and consider only the interactions with the interactions with the neighbours
* Quality of Service in Computer Networks
Show that =QoS= and /anonimity/ and /privacy/ are in costant tension.
The contract signing needs to be fair (/fair exchange/). For a pair of agents, both must succeed or both must fail.
There are limitations to network security:
- impossibility of consensus
- asynchronous setting

Solution can be a *Trusted Third Party* (=TTP=)
- it is a bottleneck
- should be fair
- should be timely
- receives signatures and distributes the contracts

=TTP= can
- issue a replacement contract
- issue an abort token
- acts only when requested
