:PROPERTIES:
:ID:       03d58ce6-d9d0-4955-b4c6-6821a5a14216
:END:
#+title: The Cowpox of Doubt
#+date: [2022-12-07 Wed 02:07]
#+filetags: article
- Source: https://slatestarcodex.com/2014/04/15/the-cowpox-of-doubt/
- Author: [[id:c0fd7c38-2a33-4988-9f43-6eee6dca1666][Slate Star Codex]]
- Related: [[id:73788b4f-c936-4424-b05c-9f78a631af51][Rationality]]

* Notes
#+begin_quote
And I worry that we are vaccinating people against reading the research for themselves instead of trusting smarmy bloggers who talk about how stupid the other side is.

That we are vaccinating people against thinking there might be important truths on both sides of an issue.

That we are vaccinating people against understanding how “scientific evidence” is a really complicated concept, and that many things that are in peer-reviewed journals will later turn out to be wrong.

That we are vaccinating people against the idea that many theories they find absurd or repugnant at first will later turn out to be true, because nature doesn’t respect our feelings.

That we are vaccinating people against doubt.

And maybe this is partly good. It’s probably a good idea to trust your doctor and also a good idea to trust your climatologist, and rare is the field where I would feel comfortable challenging expert consensus completely.
#+end_quote
- too much talk of easily debunkable stuff can be counter-productive
  - you might start to believe all falsehood is easily recognisable
- evidence is complicated
