:PROPERTIES:
:ID:       29b18999-bb4a-4131-bfc8-5a98c08acfe8
:END:
#+title: The Necessity of Marginalia in the Age of the Ebook
#+date: [2021-12-29 Wed 02:12]
#+filetags: article
- Source: https://fs.blog/marginalia/
- Author: [[id:87f4e5f5-8345-458c-b991-0821d50cbe06][Farnam Street]]
- Related: [[id:382632ea-6c46-4dc0-a02f-acd867750c8f][Marginalia]], [[id:1479941e-151a-4bd1-8b31-ee11804d220c][Note Taking]]

Marginalia, broken fragments in between our mind and the text. Instant way to chew the food that is the book, have a conversation with the book. See [[id:f259c2dc-fe03-4b66-8fa7-fbeed4260845][The Conversation We Have with Books]].

From [[id:c5bbeab2-8b11-4f77-bc87-fb4631bc9f7a][How to Read a Book]]:
#+begin_quote
    When you buy a book, you establish a property right in it, just as you do in clothes or furniture when you buy and pay for them. But the act of purchase is actually only the prelude to possession in the case of a book. Full ownership of a book only comes when you have made it a part of yourself, and the best way to make yourself a part of it— which comes to the same thing— is by writing in it.

    Why is marking a book indispensable to reading it? First, it keeps you awake— not merely conscious, but wide awake. Second, reading, if it is active, is thinking, and thinking tends to express itself in words, spoken or written. The person who says he knows what he thinks but cannot express it usually does not know what he thinks. Third, writing your reactions down helps you to remember the thoughts of the author.

    Reading a book should be a conversation between you and the author. Presumably, he knows more about the subject than you do; if not, you probably should not be bothering with his book. But understanding is a two-way operation; the learner has to question himself and question the teacher. He even has to be willing to argue with the teacher, once he understands what the teacher is saying. Marking a book is literally an expression of your differences or your agreements with the author. It is the highest respect you can pay him.
#+end_quote
