:PROPERTIES:
:ID:       ac4c7565-a9ae-4a02-af75-b59050109a96
:END:
#+title: What the F
#+date: [2022-09-24 Sat 00:15]
#+filetags: article language
- [[id:30d8bde3-80f7-4bc0-9b9d-11b0af73be0f][New Republic]]
- https://newrepublic.com/article/63921/what-the-f

- Why do politicians, editors and much of the public care about /words/ so much?
  - it's not the concepts (there are synonyms), nor the sounds
  - is profanity /corrupting/, most of all children? Thing is, to moralists in this matter, this property of this particular type of language is self-evident - there are no justifications other than that
  - the answer from progressive writers:
    - /true moralists should hold that violence and inequality are *obscene*, not sex and excretion./
  - still, in the progressive sphere have been introduced linguistic taboos of their own - such as the N-word
    - BUT, these words are part of fights for social equality and rights. They have a *political value* behind them not just a preoccupation for "decency"
- it seems /bad language/ is a relative conception
- *emotional power of swearing*
  - curses provoke a different response that their synonyms because /connotations/ and /denotations/ are stored in different parts of the brain - related: *System 1* and *System 2* in [[id:4980a886-a285-4b6a-a12d-9053aa25d536][Thinking Fast and Slow]]
  - limbic system - ancient network regulating motivation, emotion
    - likely suspect is the amygdala - it lights up when a human is shown angry faces and taboo words
  - neocortex - region highly developed in humans seat of perception, knowledge, reason, planning
  - likely: denotations in neocortex left cortex - connotations in neocortex right hemisphere and limbic system
- [[id:8208d27c-3473-4408-986c-f19005449b56][Stroop effect]] - automatic nature of speech perception forces us to consider the unpleasant connotations of words against our wil
- *historical root of swearing* in English and other languages
  - religion - /profanity/ is that which is not sacred
#+begin_quote
Blasphemy itself could not survive religion; if anyone doubts that, let him try to blaspheme Odin. [[id:42e4fdc6-7b24-4b1d-96b0-0c660fbf7b3a][#cit]] [[id:5f0770ac-76d4-4e45-8519-155daf57640e][G.C.Chesterton]]
#+end_quote
- oaths were the way people submitted a contingency to have others believe promises otherwise vain
  - religion had this function, now social and legal contracts have it
  - is US courts witnesses still have to swear on the Bible
  - although the emotional power of religion dimmed the underlying psychology is still there
- /fucking/ and derivatives are words trying to evoke the idea of exploitative sex on someone, so its not simply sex being demonized - its implying a power dynamic

#+begin_quote
You taught me language, and my profic on't is, I know how to curse. - Shakespeare's Caliban [[id:42e4fdc6-7b24-4b1d-96b0-0c660fbf7b3a][#cit]]
#+end_quote
